# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ControlPlaneDataGatewaySelectionPrimaryDetail(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ipAddress=None, logicalId=None, name=None):
        """
        ControlPlaneDataGatewaySelectionPrimaryDetail - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'ipAddress': 'str',
            'logicalId': 'str',
            'name': 'str'
        }

        self.attribute_map = {
            'ipAddress': 'ipAddress',
            'logicalId': 'logicalId',
            'name': 'name'
        }

        self._ipAddress = ipAddress
        self._logicalId = logicalId
        self._name = name

    @property
    def ipAddress(self):
        """
        Gets the ipAddress of this ControlPlaneDataGatewaySelectionPrimaryDetail.

        :return: The ipAddress of this ControlPlaneDataGatewaySelectionPrimaryDetail.
        :rtype: str
        """
        return self._ipAddress

    @ipAddress.setter
    def ipAddress(self, ipAddress):
        """
        Sets the ipAddress of this ControlPlaneDataGatewaySelectionPrimaryDetail.

        :param ipAddress: The ipAddress of this ControlPlaneDataGatewaySelectionPrimaryDetail.
        :type: str
        """

        self._ipAddress = ipAddress

    @property
    def logicalId(self):
        """
        Gets the logicalId of this ControlPlaneDataGatewaySelectionPrimaryDetail.

        :return: The logicalId of this ControlPlaneDataGatewaySelectionPrimaryDetail.
        :rtype: str
        """
        return self._logicalId

    @logicalId.setter
    def logicalId(self, logicalId):
        """
        Sets the logicalId of this ControlPlaneDataGatewaySelectionPrimaryDetail.

        :param logicalId: The logicalId of this ControlPlaneDataGatewaySelectionPrimaryDetail.
        :type: str
        """

        self._logicalId = logicalId

    @property
    def name(self):
        """
        Gets the name of this ControlPlaneDataGatewaySelectionPrimaryDetail.

        :return: The name of this ControlPlaneDataGatewaySelectionPrimaryDetail.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ControlPlaneDataGatewaySelectionPrimaryDetail.

        :param name: The name of this ControlPlaneDataGatewaySelectionPrimaryDetail.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ControlPlaneDataGatewaySelectionPrimaryDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
