# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DeviceSettingsDataModelsVirtualRoutedInterfaces(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, disabled=None, addressing=None, wanOverlay=None, natDirect=None, ospf=None, vlanId=None, l2=None, underlayAccounting=True, trusted=None, rpf=None):
        """
        DeviceSettingsDataModelsVirtualRoutedInterfaces - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'disabled': 'bool',
            'addressing': 'DeviceSettingsDataModelsVirtualAddressing',
            'wanOverlay': 'str',
            'natDirect': 'bool',
            'ospf': 'DeviceSettingsDataModelsVirtualOspf',
            'vlanId': 'int',
            'l2': 'EdgeDeviceSettingsDataL2',
            'underlayAccounting': 'bool',
            'trusted': 'bool',
            'rpf': 'str'
        }

        self.attribute_map = {
            'name': 'name',
            'disabled': 'disabled',
            'addressing': 'addressing',
            'wanOverlay': 'wanOverlay',
            'natDirect': 'natDirect',
            'ospf': 'ospf',
            'vlanId': 'vlanId',
            'l2': 'l2',
            'underlayAccounting': 'underlayAccounting',
            'trusted': 'trusted',
            'rpf': 'rpf'
        }

        self._name = name
        self._disabled = disabled
        self._addressing = addressing
        self._wanOverlay = wanOverlay
        self._natDirect = natDirect
        self._ospf = ospf
        self._vlanId = vlanId
        self._l2 = l2
        self._underlayAccounting = underlayAccounting
        self._trusted = trusted
        self._rpf = rpf

    @property
    def name(self):
        """
        Gets the name of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The name of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param name: The name of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: str
        """

        self._name = name

    @property
    def disabled(self):
        """
        Gets the disabled of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The disabled of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """
        Sets the disabled of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param disabled: The disabled of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: bool
        """

        self._disabled = disabled

    @property
    def addressing(self):
        """
        Gets the addressing of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The addressing of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: DeviceSettingsDataModelsVirtualAddressing
        """
        return self._addressing

    @addressing.setter
    def addressing(self, addressing):
        """
        Sets the addressing of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param addressing: The addressing of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: DeviceSettingsDataModelsVirtualAddressing
        """

        self._addressing = addressing

    @property
    def wanOverlay(self):
        """
        Gets the wanOverlay of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The wanOverlay of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: str
        """
        return self._wanOverlay

    @wanOverlay.setter
    def wanOverlay(self, wanOverlay):
        """
        Sets the wanOverlay of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param wanOverlay: The wanOverlay of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: str
        """

        self._wanOverlay = wanOverlay

    @property
    def natDirect(self):
        """
        Gets the natDirect of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The natDirect of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: bool
        """
        return self._natDirect

    @natDirect.setter
    def natDirect(self, natDirect):
        """
        Sets the natDirect of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param natDirect: The natDirect of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: bool
        """

        self._natDirect = natDirect

    @property
    def ospf(self):
        """
        Gets the ospf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The ospf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: DeviceSettingsDataModelsVirtualOspf
        """
        return self._ospf

    @ospf.setter
    def ospf(self, ospf):
        """
        Sets the ospf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param ospf: The ospf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: DeviceSettingsDataModelsVirtualOspf
        """

        self._ospf = ospf

    @property
    def vlanId(self):
        """
        Gets the vlanId of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The vlanId of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: int
        """
        return self._vlanId

    @vlanId.setter
    def vlanId(self, vlanId):
        """
        Sets the vlanId of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param vlanId: The vlanId of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: int
        """

        self._vlanId = vlanId

    @property
    def l2(self):
        """
        Gets the l2 of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The l2 of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: EdgeDeviceSettingsDataL2
        """
        return self._l2

    @l2.setter
    def l2(self, l2):
        """
        Sets the l2 of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param l2: The l2 of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: EdgeDeviceSettingsDataL2
        """

        self._l2 = l2

    @property
    def underlayAccounting(self):
        """
        Gets the underlayAccounting of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The underlayAccounting of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: bool
        """
        return self._underlayAccounting

    @underlayAccounting.setter
    def underlayAccounting(self, underlayAccounting):
        """
        Sets the underlayAccounting of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param underlayAccounting: The underlayAccounting of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: bool
        """

        self._underlayAccounting = underlayAccounting

    @property
    def trusted(self):
        """
        Gets the trusted of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The trusted of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: bool
        """
        return self._trusted

    @trusted.setter
    def trusted(self, trusted):
        """
        Sets the trusted of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param trusted: The trusted of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: bool
        """

        self._trusted = trusted

    @property
    def rpf(self):
        """
        Gets the rpf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :return: The rpf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :rtype: str
        """
        return self._rpf

    @rpf.setter
    def rpf(self, rpf):
        """
        Sets the rpf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.

        :param rpf: The rpf of this DeviceSettingsDataModelsVirtualRoutedInterfaces.
        :type: str
        """

        self._rpf = rpf

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DeviceSettingsDataModelsVirtualRoutedInterfaces):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
