# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DeviceSettingsDataMultiSourceQos(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, enabled=None, highRatio=None, normalRatio=None, lowRatio=None, maxCapThreshold=None, minCapThreshold=None):
        """
        DeviceSettingsDataMultiSourceQos - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'enabled': 'bool',
            'highRatio': 'int',
            'normalRatio': 'int',
            'lowRatio': 'int',
            'maxCapThreshold': 'int',
            'minCapThreshold': 'int'
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'highRatio': 'highRatio',
            'normalRatio': 'normalRatio',
            'lowRatio': 'lowRatio',
            'maxCapThreshold': 'maxCapThreshold',
            'minCapThreshold': 'minCapThreshold'
        }

        self._enabled = enabled
        self._highRatio = highRatio
        self._normalRatio = normalRatio
        self._lowRatio = lowRatio
        self._maxCapThreshold = maxCapThreshold
        self._minCapThreshold = minCapThreshold

    @property
    def enabled(self):
        """
        Gets the enabled of this DeviceSettingsDataMultiSourceQos.

        :return: The enabled of this DeviceSettingsDataMultiSourceQos.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """
        Sets the enabled of this DeviceSettingsDataMultiSourceQos.

        :param enabled: The enabled of this DeviceSettingsDataMultiSourceQos.
        :type: bool
        """

        self._enabled = enabled

    @property
    def highRatio(self):
        """
        Gets the highRatio of this DeviceSettingsDataMultiSourceQos.

        :return: The highRatio of this DeviceSettingsDataMultiSourceQos.
        :rtype: int
        """
        return self._highRatio

    @highRatio.setter
    def highRatio(self, highRatio):
        """
        Sets the highRatio of this DeviceSettingsDataMultiSourceQos.

        :param highRatio: The highRatio of this DeviceSettingsDataMultiSourceQos.
        :type: int
        """

        self._highRatio = highRatio

    @property
    def normalRatio(self):
        """
        Gets the normalRatio of this DeviceSettingsDataMultiSourceQos.

        :return: The normalRatio of this DeviceSettingsDataMultiSourceQos.
        :rtype: int
        """
        return self._normalRatio

    @normalRatio.setter
    def normalRatio(self, normalRatio):
        """
        Sets the normalRatio of this DeviceSettingsDataMultiSourceQos.

        :param normalRatio: The normalRatio of this DeviceSettingsDataMultiSourceQos.
        :type: int
        """

        self._normalRatio = normalRatio

    @property
    def lowRatio(self):
        """
        Gets the lowRatio of this DeviceSettingsDataMultiSourceQos.

        :return: The lowRatio of this DeviceSettingsDataMultiSourceQos.
        :rtype: int
        """
        return self._lowRatio

    @lowRatio.setter
    def lowRatio(self, lowRatio):
        """
        Sets the lowRatio of this DeviceSettingsDataMultiSourceQos.

        :param lowRatio: The lowRatio of this DeviceSettingsDataMultiSourceQos.
        :type: int
        """

        self._lowRatio = lowRatio

    @property
    def maxCapThreshold(self):
        """
        Gets the maxCapThreshold of this DeviceSettingsDataMultiSourceQos.

        :return: The maxCapThreshold of this DeviceSettingsDataMultiSourceQos.
        :rtype: int
        """
        return self._maxCapThreshold

    @maxCapThreshold.setter
    def maxCapThreshold(self, maxCapThreshold):
        """
        Sets the maxCapThreshold of this DeviceSettingsDataMultiSourceQos.

        :param maxCapThreshold: The maxCapThreshold of this DeviceSettingsDataMultiSourceQos.
        :type: int
        """

        self._maxCapThreshold = maxCapThreshold

    @property
    def minCapThreshold(self):
        """
        Gets the minCapThreshold of this DeviceSettingsDataMultiSourceQos.

        :return: The minCapThreshold of this DeviceSettingsDataMultiSourceQos.
        :rtype: int
        """
        return self._minCapThreshold

    @minCapThreshold.setter
    def minCapThreshold(self, minCapThreshold):
        """
        Sets the minCapThreshold of this DeviceSettingsDataMultiSourceQos.

        :param minCapThreshold: The minCapThreshold of this DeviceSettingsDataMultiSourceQos.
        :type: int
        """

        self._minCapThreshold = minCapThreshold

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DeviceSettingsDataMultiSourceQos):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
