# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EdgeDeviceSettingsDataVqm(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, enable=None, enabled=None, protocol=None, collectors=None):
        """
        EdgeDeviceSettingsDataVqm - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'enable': 'bool',
            'enabled': 'bool',
            'protocol': 'str',
            'collectors': 'list[EdgeDeviceSettingsDataNetflowCollectors]'
        }

        self.attribute_map = {
            'enable': 'enable',
            'enabled': 'enabled',
            'protocol': 'protocol',
            'collectors': 'collectors'
        }

        self._enable = enable
        self._enabled = enabled
        self._protocol = protocol
        self._collectors = collectors

    @property
    def enable(self):
        """
        Gets the enable of this EdgeDeviceSettingsDataVqm.

        :return: The enable of this EdgeDeviceSettingsDataVqm.
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable):
        """
        Sets the enable of this EdgeDeviceSettingsDataVqm.

        :param enable: The enable of this EdgeDeviceSettingsDataVqm.
        :type: bool
        """

        self._enable = enable

    @property
    def enabled(self):
        """
        Gets the enabled of this EdgeDeviceSettingsDataVqm.

        :return: The enabled of this EdgeDeviceSettingsDataVqm.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """
        Sets the enabled of this EdgeDeviceSettingsDataVqm.

        :param enabled: The enabled of this EdgeDeviceSettingsDataVqm.
        :type: bool
        """

        self._enabled = enabled

    @property
    def protocol(self):
        """
        Gets the protocol of this EdgeDeviceSettingsDataVqm.

        :return: The protocol of this EdgeDeviceSettingsDataVqm.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """
        Sets the protocol of this EdgeDeviceSettingsDataVqm.

        :param protocol: The protocol of this EdgeDeviceSettingsDataVqm.
        :type: str
        """

        self._protocol = protocol

    @property
    def collectors(self):
        """
        Gets the collectors of this EdgeDeviceSettingsDataVqm.

        :return: The collectors of this EdgeDeviceSettingsDataVqm.
        :rtype: list[EdgeDeviceSettingsDataNetflowCollectors]
        """
        return self._collectors

    @collectors.setter
    def collectors(self, collectors):
        """
        Sets the collectors of this EdgeDeviceSettingsDataVqm.

        :param collectors: The collectors of this EdgeDeviceSettingsDataVqm.
        :type: list[EdgeDeviceSettingsDataNetflowCollectors]
        """

        self._collectors = collectors

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EdgeDeviceSettingsDataVqm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
