# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EdgeDeviceSettingsDataRoutedInterfaces(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, addressing=None, advertise=None, disabled=None, dhcpServer=None, encryptOverlay=None, l2=None, name=None, natDirect=None, ospf=None, override=None, subinterfaces=None, vlanId=None, wanOverlay=None, trusted=None, rpf=None, underlayAccounting=True):
        """
        EdgeDeviceSettingsDataRoutedInterfaces - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'addressing': 'EdgeDeviceSettingsDataAddressing',
            'advertise': 'bool',
            'disabled': 'bool',
            'dhcpServer': 'EdgeDeviceSettingsDataDhcpServer',
            'encryptOverlay': 'bool',
            'l2': 'EdgeDeviceSettingsDataL2',
            'name': 'str',
            'natDirect': 'bool',
            'ospf': 'EdgeDeviceSettingsDataOspf',
            'override': 'bool',
            'subinterfaces': 'list[EdgeDeviceSettingsDataSubinterfaces]',
            'vlanId': 'int',
            'wanOverlay': 'str',
            'trusted': 'bool',
            'rpf': 'str',
            'underlayAccounting': 'bool'
        }

        self.attribute_map = {
            'addressing': 'addressing',
            'advertise': 'advertise',
            'disabled': 'disabled',
            'dhcpServer': 'dhcpServer',
            'encryptOverlay': 'encryptOverlay',
            'l2': 'l2',
            'name': 'name',
            'natDirect': 'natDirect',
            'ospf': 'ospf',
            'override': 'override',
            'subinterfaces': 'subinterfaces',
            'vlanId': 'vlanId',
            'wanOverlay': 'wanOverlay',
            'trusted': 'trusted',
            'rpf': 'rpf',
            'underlayAccounting': 'underlayAccounting'
        }

        self._addressing = addressing
        self._advertise = advertise
        self._disabled = disabled
        self._dhcpServer = dhcpServer
        self._encryptOverlay = encryptOverlay
        self._l2 = l2
        self._name = name
        self._natDirect = natDirect
        self._ospf = ospf
        self._override = override
        self._subinterfaces = subinterfaces
        self._vlanId = vlanId
        self._wanOverlay = wanOverlay
        self._trusted = trusted
        self._rpf = rpf
        self._underlayAccounting = underlayAccounting

    @property
    def addressing(self):
        """
        Gets the addressing of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The addressing of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: EdgeDeviceSettingsDataAddressing
        """
        return self._addressing

    @addressing.setter
    def addressing(self, addressing):
        """
        Sets the addressing of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param addressing: The addressing of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: EdgeDeviceSettingsDataAddressing
        """

        self._addressing = addressing

    @property
    def advertise(self):
        """
        Gets the advertise of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The advertise of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: bool
        """
        return self._advertise

    @advertise.setter
    def advertise(self, advertise):
        """
        Sets the advertise of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param advertise: The advertise of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: bool
        """

        self._advertise = advertise

    @property
    def disabled(self):
        """
        Gets the disabled of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The disabled of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """
        Sets the disabled of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param disabled: The disabled of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: bool
        """

        self._disabled = disabled

    @property
    def dhcpServer(self):
        """
        Gets the dhcpServer of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The dhcpServer of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: EdgeDeviceSettingsDataDhcpServer
        """
        return self._dhcpServer

    @dhcpServer.setter
    def dhcpServer(self, dhcpServer):
        """
        Sets the dhcpServer of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param dhcpServer: The dhcpServer of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: EdgeDeviceSettingsDataDhcpServer
        """

        self._dhcpServer = dhcpServer

    @property
    def encryptOverlay(self):
        """
        Gets the encryptOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The encryptOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: bool
        """
        return self._encryptOverlay

    @encryptOverlay.setter
    def encryptOverlay(self, encryptOverlay):
        """
        Sets the encryptOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param encryptOverlay: The encryptOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: bool
        """

        self._encryptOverlay = encryptOverlay

    @property
    def l2(self):
        """
        Gets the l2 of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The l2 of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: EdgeDeviceSettingsDataL2
        """
        return self._l2

    @l2.setter
    def l2(self, l2):
        """
        Sets the l2 of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param l2: The l2 of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: EdgeDeviceSettingsDataL2
        """

        self._l2 = l2

    @property
    def name(self):
        """
        Gets the name of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The name of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param name: The name of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: str
        """

        self._name = name

    @property
    def natDirect(self):
        """
        Gets the natDirect of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The natDirect of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: bool
        """
        return self._natDirect

    @natDirect.setter
    def natDirect(self, natDirect):
        """
        Sets the natDirect of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param natDirect: The natDirect of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: bool
        """

        self._natDirect = natDirect

    @property
    def ospf(self):
        """
        Gets the ospf of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The ospf of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: EdgeDeviceSettingsDataOspf
        """
        return self._ospf

    @ospf.setter
    def ospf(self, ospf):
        """
        Sets the ospf of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param ospf: The ospf of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: EdgeDeviceSettingsDataOspf
        """

        self._ospf = ospf

    @property
    def override(self):
        """
        Gets the override of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The override of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: bool
        """
        return self._override

    @override.setter
    def override(self, override):
        """
        Sets the override of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param override: The override of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: bool
        """

        self._override = override

    @property
    def subinterfaces(self):
        """
        Gets the subinterfaces of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The subinterfaces of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: list[EdgeDeviceSettingsDataSubinterfaces]
        """
        return self._subinterfaces

    @subinterfaces.setter
    def subinterfaces(self, subinterfaces):
        """
        Sets the subinterfaces of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param subinterfaces: The subinterfaces of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: list[EdgeDeviceSettingsDataSubinterfaces]
        """

        self._subinterfaces = subinterfaces

    @property
    def vlanId(self):
        """
        Gets the vlanId of this EdgeDeviceSettingsDataRoutedInterfaces.
        static only

        :return: The vlanId of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: int
        """
        return self._vlanId

    @vlanId.setter
    def vlanId(self, vlanId):
        """
        Sets the vlanId of this EdgeDeviceSettingsDataRoutedInterfaces.
        static only

        :param vlanId: The vlanId of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: int
        """

        self._vlanId = vlanId

    @property
    def wanOverlay(self):
        """
        Gets the wanOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The wanOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: str
        """
        return self._wanOverlay

    @wanOverlay.setter
    def wanOverlay(self, wanOverlay):
        """
        Sets the wanOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param wanOverlay: The wanOverlay of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: str
        """

        self._wanOverlay = wanOverlay

    @property
    def trusted(self):
        """
        Gets the trusted of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The trusted of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: bool
        """
        return self._trusted

    @trusted.setter
    def trusted(self, trusted):
        """
        Sets the trusted of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param trusted: The trusted of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: bool
        """

        self._trusted = trusted

    @property
    def rpf(self):
        """
        Gets the rpf of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The rpf of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: str
        """
        return self._rpf

    @rpf.setter
    def rpf(self, rpf):
        """
        Sets the rpf of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param rpf: The rpf of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: str
        """

        self._rpf = rpf

    @property
    def underlayAccounting(self):
        """
        Gets the underlayAccounting of this EdgeDeviceSettingsDataRoutedInterfaces.

        :return: The underlayAccounting of this EdgeDeviceSettingsDataRoutedInterfaces.
        :rtype: bool
        """
        return self._underlayAccounting

    @underlayAccounting.setter
    def underlayAccounting(self, underlayAccounting):
        """
        Sets the underlayAccounting of this EdgeDeviceSettingsDataRoutedInterfaces.

        :param underlayAccounting: The underlayAccounting of this EdgeDeviceSettingsDataRoutedInterfaces.
        :type: bool
        """

        self._underlayAccounting = underlayAccounting

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EdgeDeviceSettingsDataRoutedInterfaces):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
