# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EdgeQOSDataCosMapping(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, lsInputType=None, bulk=None, realtime=None, transactional=None):
        """
        EdgeQOSDataCosMapping - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'lsInputType': 'str',
            'bulk': 'CosMapping',
            'realtime': 'CosMapping',
            'transactional': 'CosMapping'
        }

        self.attribute_map = {
            'lsInputType': 'lsInputType',
            'bulk': 'bulk',
            'realtime': 'realtime',
            'transactional': 'transactional'
        }

        self._lsInputType = lsInputType
        self._bulk = bulk
        self._realtime = realtime
        self._transactional = transactional

    @property
    def lsInputType(self):
        """
        Gets the lsInputType of this EdgeQOSDataCosMapping.

        :return: The lsInputType of this EdgeQOSDataCosMapping.
        :rtype: str
        """
        return self._lsInputType

    @lsInputType.setter
    def lsInputType(self, lsInputType):
        """
        Sets the lsInputType of this EdgeQOSDataCosMapping.

        :param lsInputType: The lsInputType of this EdgeQOSDataCosMapping.
        :type: str
        """

        self._lsInputType = lsInputType

    @property
    def bulk(self):
        """
        Gets the bulk of this EdgeQOSDataCosMapping.

        :return: The bulk of this EdgeQOSDataCosMapping.
        :rtype: CosMapping
        """
        return self._bulk

    @bulk.setter
    def bulk(self, bulk):
        """
        Sets the bulk of this EdgeQOSDataCosMapping.

        :param bulk: The bulk of this EdgeQOSDataCosMapping.
        :type: CosMapping
        """

        self._bulk = bulk

    @property
    def realtime(self):
        """
        Gets the realtime of this EdgeQOSDataCosMapping.

        :return: The realtime of this EdgeQOSDataCosMapping.
        :rtype: CosMapping
        """
        return self._realtime

    @realtime.setter
    def realtime(self, realtime):
        """
        Sets the realtime of this EdgeQOSDataCosMapping.

        :param realtime: The realtime of this EdgeQOSDataCosMapping.
        :type: CosMapping
        """

        self._realtime = realtime

    @property
    def transactional(self):
        """
        Gets the transactional of this EdgeQOSDataCosMapping.

        :return: The transactional of this EdgeQOSDataCosMapping.
        :rtype: CosMapping
        """
        return self._transactional

    @transactional.setter
    def transactional(self, transactional):
        """
        Sets the transactional of this EdgeQOSDataCosMapping.

        :param transactional: The transactional of this EdgeQOSDataCosMapping.
        :type: CosMapping
        """

        self._transactional = transactional

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EdgeQOSDataCosMapping):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
