# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EdgeDeviceSettingsDataAddressing1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, cidrIp=None, cidrPrefix=None, gateway=None, netmask=None, type=None, username=None, password=None):
        """
        EdgeDeviceSettingsDataAddressing1 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'cidrIp': 'str',
            'cidrPrefix': 'int',
            'gateway': 'str',
            'netmask': 'str',
            'type': 'str',
            'username': 'str',
            'password': 'str'
        }

        self.attribute_map = {
            'cidrIp': 'cidrIp',
            'cidrPrefix': 'cidrPrefix',
            'gateway': 'gateway',
            'netmask': 'netmask',
            'type': 'type',
            'username': 'username',
            'password': 'password'
        }

        self._cidrIp = cidrIp
        self._cidrPrefix = cidrPrefix
        self._gateway = gateway
        self._netmask = netmask
        self._type = type
        self._username = username
        self._password = password

    @property
    def cidrIp(self):
        """
        Gets the cidrIp of this EdgeDeviceSettingsDataAddressing1.

        :return: The cidrIp of this EdgeDeviceSettingsDataAddressing1.
        :rtype: str
        """
        return self._cidrIp

    @cidrIp.setter
    def cidrIp(self, cidrIp):
        """
        Sets the cidrIp of this EdgeDeviceSettingsDataAddressing1.

        :param cidrIp: The cidrIp of this EdgeDeviceSettingsDataAddressing1.
        :type: str
        """

        self._cidrIp = cidrIp

    @property
    def cidrPrefix(self):
        """
        Gets the cidrPrefix of this EdgeDeviceSettingsDataAddressing1.

        :return: The cidrPrefix of this EdgeDeviceSettingsDataAddressing1.
        :rtype: int
        """
        return self._cidrPrefix

    @cidrPrefix.setter
    def cidrPrefix(self, cidrPrefix):
        """
        Sets the cidrPrefix of this EdgeDeviceSettingsDataAddressing1.

        :param cidrPrefix: The cidrPrefix of this EdgeDeviceSettingsDataAddressing1.
        :type: int
        """

        self._cidrPrefix = cidrPrefix

    @property
    def gateway(self):
        """
        Gets the gateway of this EdgeDeviceSettingsDataAddressing1.

        :return: The gateway of this EdgeDeviceSettingsDataAddressing1.
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """
        Sets the gateway of this EdgeDeviceSettingsDataAddressing1.

        :param gateway: The gateway of this EdgeDeviceSettingsDataAddressing1.
        :type: str
        """

        self._gateway = gateway

    @property
    def netmask(self):
        """
        Gets the netmask of this EdgeDeviceSettingsDataAddressing1.

        :return: The netmask of this EdgeDeviceSettingsDataAddressing1.
        :rtype: str
        """
        return self._netmask

    @netmask.setter
    def netmask(self, netmask):
        """
        Sets the netmask of this EdgeDeviceSettingsDataAddressing1.

        :param netmask: The netmask of this EdgeDeviceSettingsDataAddressing1.
        :type: str
        """

        self._netmask = netmask

    @property
    def type(self):
        """
        Gets the type of this EdgeDeviceSettingsDataAddressing1.

        :return: The type of this EdgeDeviceSettingsDataAddressing1.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this EdgeDeviceSettingsDataAddressing1.

        :param type: The type of this EdgeDeviceSettingsDataAddressing1.
        :type: str
        """

        self._type = type

    @property
    def username(self):
        """
        Gets the username of this EdgeDeviceSettingsDataAddressing1.

        :return: The username of this EdgeDeviceSettingsDataAddressing1.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this EdgeDeviceSettingsDataAddressing1.

        :param username: The username of this EdgeDeviceSettingsDataAddressing1.
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """
        Gets the password of this EdgeDeviceSettingsDataAddressing1.

        :return: The password of this EdgeDeviceSettingsDataAddressing1.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this EdgeDeviceSettingsDataAddressing1.

        :param password: The password of this EdgeDeviceSettingsDataAddressing1.
        :type: str
        """

        self._password = password

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EdgeDeviceSettingsDataAddressing1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
