# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EdgeDeviceSettingsDataSnmp(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, port=None, snmpv2c=None, snmpv3=None):
        """
        EdgeDeviceSettingsDataSnmp - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'port': 'int',
            'snmpv2c': 'EdgeDeviceSettingsDataSnmpSnmpv2c',
            'snmpv3': 'EdgeDeviceSettingsDataSnmpSnmpv3'
        }

        self.attribute_map = {
            'port': 'port',
            'snmpv2c': 'snmpv2c',
            'snmpv3': 'snmpv3'
        }

        self._port = port
        self._snmpv2c = snmpv2c
        self._snmpv3 = snmpv3

    @property
    def port(self):
        """
        Gets the port of this EdgeDeviceSettingsDataSnmp.

        :return: The port of this EdgeDeviceSettingsDataSnmp.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """
        Sets the port of this EdgeDeviceSettingsDataSnmp.

        :param port: The port of this EdgeDeviceSettingsDataSnmp.
        :type: int
        """

        self._port = port

    @property
    def snmpv2c(self):
        """
        Gets the snmpv2c of this EdgeDeviceSettingsDataSnmp.

        :return: The snmpv2c of this EdgeDeviceSettingsDataSnmp.
        :rtype: EdgeDeviceSettingsDataSnmpSnmpv2c
        """
        return self._snmpv2c

    @snmpv2c.setter
    def snmpv2c(self, snmpv2c):
        """
        Sets the snmpv2c of this EdgeDeviceSettingsDataSnmp.

        :param snmpv2c: The snmpv2c of this EdgeDeviceSettingsDataSnmp.
        :type: EdgeDeviceSettingsDataSnmpSnmpv2c
        """

        self._snmpv2c = snmpv2c

    @property
    def snmpv3(self):
        """
        Gets the snmpv3 of this EdgeDeviceSettingsDataSnmp.

        :return: The snmpv3 of this EdgeDeviceSettingsDataSnmp.
        :rtype: EdgeDeviceSettingsDataSnmpSnmpv3
        """
        return self._snmpv3

    @snmpv3.setter
    def snmpv3(self, snmpv3):
        """
        Sets the snmpv3 of this EdgeDeviceSettingsDataSnmp.

        :param snmpv3: The snmpv3 of this EdgeDeviceSettingsDataSnmp.
        :type: EdgeDeviceSettingsDataSnmpSnmpv3
        """

        self._snmpv3 = snmpv3

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EdgeDeviceSettingsDataSnmp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
