# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EdgeDeviceSettingsDataDns(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, primaryProvider=None, backupProvider=None, privateProviders=None):
        """
        EdgeDeviceSettingsDataDns - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'primaryProvider': 'EdgeDeviceSettingsDataDnsPrimaryProvider',
            'backupProvider': 'EdgeDeviceSettingsDataDnsPrimaryProvider',
            'privateProviders': 'EdgeDeviceSettingsDataDnsPrimaryProvider'
        }

        self.attribute_map = {
            'primaryProvider': 'primaryProvider',
            'backupProvider': 'backupProvider',
            'privateProviders': 'privateProviders'
        }

        self._primaryProvider = primaryProvider
        self._backupProvider = backupProvider
        self._privateProviders = privateProviders

    @property
    def primaryProvider(self):
        """
        Gets the primaryProvider of this EdgeDeviceSettingsDataDns.

        :return: The primaryProvider of this EdgeDeviceSettingsDataDns.
        :rtype: EdgeDeviceSettingsDataDnsPrimaryProvider
        """
        return self._primaryProvider

    @primaryProvider.setter
    def primaryProvider(self, primaryProvider):
        """
        Sets the primaryProvider of this EdgeDeviceSettingsDataDns.

        :param primaryProvider: The primaryProvider of this EdgeDeviceSettingsDataDns.
        :type: EdgeDeviceSettingsDataDnsPrimaryProvider
        """

        self._primaryProvider = primaryProvider

    @property
    def backupProvider(self):
        """
        Gets the backupProvider of this EdgeDeviceSettingsDataDns.

        :return: The backupProvider of this EdgeDeviceSettingsDataDns.
        :rtype: EdgeDeviceSettingsDataDnsPrimaryProvider
        """
        return self._backupProvider

    @backupProvider.setter
    def backupProvider(self, backupProvider):
        """
        Sets the backupProvider of this EdgeDeviceSettingsDataDns.

        :param backupProvider: The backupProvider of this EdgeDeviceSettingsDataDns.
        :type: EdgeDeviceSettingsDataDnsPrimaryProvider
        """

        self._backupProvider = backupProvider

    @property
    def privateProviders(self):
        """
        Gets the privateProviders of this EdgeDeviceSettingsDataDns.

        :return: The privateProviders of this EdgeDeviceSettingsDataDns.
        :rtype: EdgeDeviceSettingsDataDnsPrimaryProvider
        """
        return self._privateProviders

    @privateProviders.setter
    def privateProviders(self, privateProviders):
        """
        Sets the privateProviders of this EdgeDeviceSettingsDataDns.

        :param privateProviders: The privateProviders of this EdgeDeviceSettingsDataDns.
        :type: EdgeDeviceSettingsDataDnsPrimaryProvider
        """

        self._privateProviders = privateProviders

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EdgeDeviceSettingsDataDns):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
