# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EnterpriseProxyGetEnterpriseProxyEdgeInventory(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, enterpriseProxyId=None):
        """
        EnterpriseProxyGetEnterpriseProxyEdgeInventory - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'enterpriseProxyId': 'int'
        }

        self.attribute_map = {
            'enterpriseProxyId': 'enterpriseProxyId'
        }

        self._enterpriseProxyId = enterpriseProxyId

    @property
    def enterpriseProxyId(self):
        """
        Gets the enterpriseProxyId of this EnterpriseProxyGetEnterpriseProxyEdgeInventory.

        :return: The enterpriseProxyId of this EnterpriseProxyGetEnterpriseProxyEdgeInventory.
        :rtype: int
        """
        return self._enterpriseProxyId

    @enterpriseProxyId.setter
    def enterpriseProxyId(self, enterpriseProxyId):
        """
        Sets the enterpriseProxyId of this EnterpriseProxyGetEnterpriseProxyEdgeInventory.

        :param enterpriseProxyId: The enterpriseProxyId of this EnterpriseProxyGetEnterpriseProxyEdgeInventory.
        :type: int
        """

        self._enterpriseProxyId = enterpriseProxyId

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EnterpriseProxyGetEnterpriseProxyEdgeInventory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
