# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EnterpriseRoute(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, exitType=None, edgeId=None, edgeName=None, profileId=None, cidrIp=None, cost=None, advertise=None):
        """
        EnterpriseRoute - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'exitType': 'str',
            'edgeId': 'int',
            'edgeName': 'str',
            'profileId': 'int',
            'cidrIp': 'str',
            'cost': 'int',
            'advertise': 'bool'
        }

        self.attribute_map = {
            'type': 'type',
            'exitType': 'exitType',
            'edgeId': 'edgeId',
            'edgeName': 'edgeName',
            'profileId': 'profileId',
            'cidrIp': 'cidrIp',
            'cost': 'cost',
            'advertise': 'advertise'
        }

        self._type = type
        self._exitType = exitType
        self._edgeId = edgeId
        self._edgeName = edgeName
        self._profileId = profileId
        self._cidrIp = cidrIp
        self._cost = cost
        self._advertise = advertise

    @property
    def type(self):
        """
        Gets the type of this EnterpriseRoute.

        :return: The type of this EnterpriseRoute.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this EnterpriseRoute.

        :param type: The type of this EnterpriseRoute.
        :type: str
        """

        self._type = type

    @property
    def exitType(self):
        """
        Gets the exitType of this EnterpriseRoute.

        :return: The exitType of this EnterpriseRoute.
        :rtype: str
        """
        return self._exitType

    @exitType.setter
    def exitType(self, exitType):
        """
        Sets the exitType of this EnterpriseRoute.

        :param exitType: The exitType of this EnterpriseRoute.
        :type: str
        """

        self._exitType = exitType

    @property
    def edgeId(self):
        """
        Gets the edgeId of this EnterpriseRoute.

        :return: The edgeId of this EnterpriseRoute.
        :rtype: int
        """
        return self._edgeId

    @edgeId.setter
    def edgeId(self, edgeId):
        """
        Sets the edgeId of this EnterpriseRoute.

        :param edgeId: The edgeId of this EnterpriseRoute.
        :type: int
        """

        self._edgeId = edgeId

    @property
    def edgeName(self):
        """
        Gets the edgeName of this EnterpriseRoute.

        :return: The edgeName of this EnterpriseRoute.
        :rtype: str
        """
        return self._edgeName

    @edgeName.setter
    def edgeName(self, edgeName):
        """
        Sets the edgeName of this EnterpriseRoute.

        :param edgeName: The edgeName of this EnterpriseRoute.
        :type: str
        """

        self._edgeName = edgeName

    @property
    def profileId(self):
        """
        Gets the profileId of this EnterpriseRoute.

        :return: The profileId of this EnterpriseRoute.
        :rtype: int
        """
        return self._profileId

    @profileId.setter
    def profileId(self, profileId):
        """
        Sets the profileId of this EnterpriseRoute.

        :param profileId: The profileId of this EnterpriseRoute.
        :type: int
        """

        self._profileId = profileId

    @property
    def cidrIp(self):
        """
        Gets the cidrIp of this EnterpriseRoute.

        :return: The cidrIp of this EnterpriseRoute.
        :rtype: str
        """
        return self._cidrIp

    @cidrIp.setter
    def cidrIp(self, cidrIp):
        """
        Sets the cidrIp of this EnterpriseRoute.

        :param cidrIp: The cidrIp of this EnterpriseRoute.
        :type: str
        """

        self._cidrIp = cidrIp

    @property
    def cost(self):
        """
        Gets the cost of this EnterpriseRoute.

        :return: The cost of this EnterpriseRoute.
        :rtype: int
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """
        Sets the cost of this EnterpriseRoute.

        :param cost: The cost of this EnterpriseRoute.
        :type: int
        """

        self._cost = cost

    @property
    def advertise(self):
        """
        Gets the advertise of this EnterpriseRoute.

        :return: The advertise of this EnterpriseRoute.
        :rtype: bool
        """
        return self._advertise

    @advertise.setter
    def advertise(self, advertise):
        """
        Sets the advertise of this EnterpriseRoute.

        :param advertise: The advertise of this EnterpriseRoute.
        :type: bool
        """

        self._advertise = advertise

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EnterpriseRoute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
