# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EnterpriseProxy(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, created=None, networkId=None, proxyType=None, operateGateways=None, logicalId=None, name=None, domain=None, prefix=None, description=None, contactName=None, contactPhone=None, contactMobile=None, contactEmail=None, streetAddress=None, streetAddress2=None, city=None, state=None, postalCode=None, country=None, lat=None, lon=None, modified=None):
        """
        EnterpriseProxy - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'created': 'datetime',
            'networkId': 'int',
            'proxyType': 'str',
            'operateGateways': 'bool',
            'logicalId': 'str',
            'name': 'str',
            'domain': 'str',
            'prefix': 'str',
            'description': 'str',
            'contactName': 'str',
            'contactPhone': 'str',
            'contactMobile': 'str',
            'contactEmail': 'str',
            'streetAddress': 'str',
            'streetAddress2': 'str',
            'city': 'str',
            'state': 'str',
            'postalCode': 'str',
            'country': 'str',
            'lat': 'float',
            'lon': 'float',
            'modified': 'datetime'
        }

        self.attribute_map = {
            'id': 'id',
            'created': 'created',
            'networkId': 'networkId',
            'proxyType': 'proxyType',
            'operateGateways': 'operateGateways',
            'logicalId': 'logicalId',
            'name': 'name',
            'domain': 'domain',
            'prefix': 'prefix',
            'description': 'description',
            'contactName': 'contactName',
            'contactPhone': 'contactPhone',
            'contactMobile': 'contactMobile',
            'contactEmail': 'contactEmail',
            'streetAddress': 'streetAddress',
            'streetAddress2': 'streetAddress2',
            'city': 'city',
            'state': 'state',
            'postalCode': 'postalCode',
            'country': 'country',
            'lat': 'lat',
            'lon': 'lon',
            'modified': 'modified'
        }

        self._id = id
        self._created = created
        self._networkId = networkId
        self._proxyType = proxyType
        self._operateGateways = operateGateways
        self._logicalId = logicalId
        self._name = name
        self._domain = domain
        self._prefix = prefix
        self._description = description
        self._contactName = contactName
        self._contactPhone = contactPhone
        self._contactMobile = contactMobile
        self._contactEmail = contactEmail
        self._streetAddress = streetAddress
        self._streetAddress2 = streetAddress2
        self._city = city
        self._state = state
        self._postalCode = postalCode
        self._country = country
        self._lat = lat
        self._lon = lon
        self._modified = modified

    @property
    def id(self):
        """
        Gets the id of this EnterpriseProxy.

        :return: The id of this EnterpriseProxy.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this EnterpriseProxy.

        :param id: The id of this EnterpriseProxy.
        :type: int
        """

        self._id = id

    @property
    def created(self):
        """
        Gets the created of this EnterpriseProxy.

        :return: The created of this EnterpriseProxy.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this EnterpriseProxy.

        :param created: The created of this EnterpriseProxy.
        :type: datetime
        """

        self._created = created

    @property
    def networkId(self):
        """
        Gets the networkId of this EnterpriseProxy.

        :return: The networkId of this EnterpriseProxy.
        :rtype: int
        """
        return self._networkId

    @networkId.setter
    def networkId(self, networkId):
        """
        Sets the networkId of this EnterpriseProxy.

        :param networkId: The networkId of this EnterpriseProxy.
        :type: int
        """

        self._networkId = networkId

    @property
    def proxyType(self):
        """
        Gets the proxyType of this EnterpriseProxy.

        :return: The proxyType of this EnterpriseProxy.
        :rtype: str
        """
        return self._proxyType

    @proxyType.setter
    def proxyType(self, proxyType):
        """
        Sets the proxyType of this EnterpriseProxy.

        :param proxyType: The proxyType of this EnterpriseProxy.
        :type: str
        """

        self._proxyType = proxyType

    @property
    def operateGateways(self):
        """
        Gets the operateGateways of this EnterpriseProxy.

        :return: The operateGateways of this EnterpriseProxy.
        :rtype: bool
        """
        return self._operateGateways

    @operateGateways.setter
    def operateGateways(self, operateGateways):
        """
        Sets the operateGateways of this EnterpriseProxy.

        :param operateGateways: The operateGateways of this EnterpriseProxy.
        :type: bool
        """

        self._operateGateways = operateGateways

    @property
    def logicalId(self):
        """
        Gets the logicalId of this EnterpriseProxy.

        :return: The logicalId of this EnterpriseProxy.
        :rtype: str
        """
        return self._logicalId

    @logicalId.setter
    def logicalId(self, logicalId):
        """
        Sets the logicalId of this EnterpriseProxy.

        :param logicalId: The logicalId of this EnterpriseProxy.
        :type: str
        """

        self._logicalId = logicalId

    @property
    def name(self):
        """
        Gets the name of this EnterpriseProxy.

        :return: The name of this EnterpriseProxy.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this EnterpriseProxy.

        :param name: The name of this EnterpriseProxy.
        :type: str
        """

        self._name = name

    @property
    def domain(self):
        """
        Gets the domain of this EnterpriseProxy.

        :return: The domain of this EnterpriseProxy.
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """
        Sets the domain of this EnterpriseProxy.

        :param domain: The domain of this EnterpriseProxy.
        :type: str
        """

        self._domain = domain

    @property
    def prefix(self):
        """
        Gets the prefix of this EnterpriseProxy.

        :return: The prefix of this EnterpriseProxy.
        :rtype: str
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix):
        """
        Sets the prefix of this EnterpriseProxy.

        :param prefix: The prefix of this EnterpriseProxy.
        :type: str
        """

        self._prefix = prefix

    @property
    def description(self):
        """
        Gets the description of this EnterpriseProxy.

        :return: The description of this EnterpriseProxy.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this EnterpriseProxy.

        :param description: The description of this EnterpriseProxy.
        :type: str
        """

        self._description = description

    @property
    def contactName(self):
        """
        Gets the contactName of this EnterpriseProxy.

        :return: The contactName of this EnterpriseProxy.
        :rtype: str
        """
        return self._contactName

    @contactName.setter
    def contactName(self, contactName):
        """
        Sets the contactName of this EnterpriseProxy.

        :param contactName: The contactName of this EnterpriseProxy.
        :type: str
        """

        self._contactName = contactName

    @property
    def contactPhone(self):
        """
        Gets the contactPhone of this EnterpriseProxy.

        :return: The contactPhone of this EnterpriseProxy.
        :rtype: str
        """
        return self._contactPhone

    @contactPhone.setter
    def contactPhone(self, contactPhone):
        """
        Sets the contactPhone of this EnterpriseProxy.

        :param contactPhone: The contactPhone of this EnterpriseProxy.
        :type: str
        """

        self._contactPhone = contactPhone

    @property
    def contactMobile(self):
        """
        Gets the contactMobile of this EnterpriseProxy.

        :return: The contactMobile of this EnterpriseProxy.
        :rtype: str
        """
        return self._contactMobile

    @contactMobile.setter
    def contactMobile(self, contactMobile):
        """
        Sets the contactMobile of this EnterpriseProxy.

        :param contactMobile: The contactMobile of this EnterpriseProxy.
        :type: str
        """

        self._contactMobile = contactMobile

    @property
    def contactEmail(self):
        """
        Gets the contactEmail of this EnterpriseProxy.

        :return: The contactEmail of this EnterpriseProxy.
        :rtype: str
        """
        return self._contactEmail

    @contactEmail.setter
    def contactEmail(self, contactEmail):
        """
        Sets the contactEmail of this EnterpriseProxy.

        :param contactEmail: The contactEmail of this EnterpriseProxy.
        :type: str
        """

        self._contactEmail = contactEmail

    @property
    def streetAddress(self):
        """
        Gets the streetAddress of this EnterpriseProxy.

        :return: The streetAddress of this EnterpriseProxy.
        :rtype: str
        """
        return self._streetAddress

    @streetAddress.setter
    def streetAddress(self, streetAddress):
        """
        Sets the streetAddress of this EnterpriseProxy.

        :param streetAddress: The streetAddress of this EnterpriseProxy.
        :type: str
        """

        self._streetAddress = streetAddress

    @property
    def streetAddress2(self):
        """
        Gets the streetAddress2 of this EnterpriseProxy.

        :return: The streetAddress2 of this EnterpriseProxy.
        :rtype: str
        """
        return self._streetAddress2

    @streetAddress2.setter
    def streetAddress2(self, streetAddress2):
        """
        Sets the streetAddress2 of this EnterpriseProxy.

        :param streetAddress2: The streetAddress2 of this EnterpriseProxy.
        :type: str
        """

        self._streetAddress2 = streetAddress2

    @property
    def city(self):
        """
        Gets the city of this EnterpriseProxy.

        :return: The city of this EnterpriseProxy.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """
        Sets the city of this EnterpriseProxy.

        :param city: The city of this EnterpriseProxy.
        :type: str
        """

        self._city = city

    @property
    def state(self):
        """
        Gets the state of this EnterpriseProxy.

        :return: The state of this EnterpriseProxy.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this EnterpriseProxy.

        :param state: The state of this EnterpriseProxy.
        :type: str
        """

        self._state = state

    @property
    def postalCode(self):
        """
        Gets the postalCode of this EnterpriseProxy.

        :return: The postalCode of this EnterpriseProxy.
        :rtype: str
        """
        return self._postalCode

    @postalCode.setter
    def postalCode(self, postalCode):
        """
        Sets the postalCode of this EnterpriseProxy.

        :param postalCode: The postalCode of this EnterpriseProxy.
        :type: str
        """

        self._postalCode = postalCode

    @property
    def country(self):
        """
        Gets the country of this EnterpriseProxy.

        :return: The country of this EnterpriseProxy.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """
        Sets the country of this EnterpriseProxy.

        :param country: The country of this EnterpriseProxy.
        :type: str
        """

        self._country = country

    @property
    def lat(self):
        """
        Gets the lat of this EnterpriseProxy.

        :return: The lat of this EnterpriseProxy.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """
        Sets the lat of this EnterpriseProxy.

        :param lat: The lat of this EnterpriseProxy.
        :type: float
        """

        self._lat = lat

    @property
    def lon(self):
        """
        Gets the lon of this EnterpriseProxy.

        :return: The lon of this EnterpriseProxy.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """
        Sets the lon of this EnterpriseProxy.

        :param lon: The lon of this EnterpriseProxy.
        :type: float
        """

        self._lon = lon

    @property
    def modified(self):
        """
        Gets the modified of this EnterpriseProxy.

        :return: The modified of this EnterpriseProxy.
        :rtype: datetime
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """
        Sets the modified of this EnterpriseProxy.

        :param modified: The modified of this EnterpriseProxy.
        :type: datetime
        """

        self._modified = modified

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EnterpriseProxy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
