# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, advertiseInternal=True, advertiseExternal=False, advertiseNeighborTags=None):
        """
        EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'advertiseInternal': 'bool',
            'advertiseExternal': 'bool',
            'advertiseNeighborTags': 'EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgpAdvertiseNeighborTags'
        }

        self.attribute_map = {
            'advertiseInternal': 'advertiseInternal',
            'advertiseExternal': 'advertiseExternal',
            'advertiseNeighborTags': 'advertiseNeighborTags'
        }

        self._advertiseInternal = advertiseInternal
        self._advertiseExternal = advertiseExternal
        self._advertiseNeighborTags = advertiseNeighborTags

    @property
    def advertiseInternal(self):
        """
        Gets the advertiseInternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.

        :return: The advertiseInternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.
        :rtype: bool
        """
        return self._advertiseInternal

    @advertiseInternal.setter
    def advertiseInternal(self, advertiseInternal):
        """
        Sets the advertiseInternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.

        :param advertiseInternal: The advertiseInternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.
        :type: bool
        """

        self._advertiseInternal = advertiseInternal

    @property
    def advertiseExternal(self):
        """
        Gets the advertiseExternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.

        :return: The advertiseExternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.
        :rtype: bool
        """
        return self._advertiseExternal

    @advertiseExternal.setter
    def advertiseExternal(self, advertiseExternal):
        """
        Sets the advertiseExternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.

        :param advertiseExternal: The advertiseExternal of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.
        :type: bool
        """

        self._advertiseExternal = advertiseExternal

    @property
    def advertiseNeighborTags(self):
        """
        Gets the advertiseNeighborTags of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.

        :return: The advertiseNeighborTags of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.
        :rtype: EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgpAdvertiseNeighborTags
        """
        return self._advertiseNeighborTags

    @advertiseNeighborTags.setter
    def advertiseNeighborTags(self, advertiseNeighborTags):
        """
        Sets the advertiseNeighborTags of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.

        :param advertiseNeighborTags: The advertiseNeighborTags of this EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp.
        :type: EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgpAdvertiseNeighborTags
        """

        self._advertiseNeighborTags = advertiseNeighborTags

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EnterpriseupdateEnterpriseRouteConfigurationDataEdgeBgp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
