# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EnterpriseSetEnterpriseAllAlertRecipients(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, enterpriseId=None, enterpriseUsers=None, smsEnabled=None, smsList=None, emailEnabled=None, emailList=None, mobileEnabled=None, mobileList=None):
        """
        EnterpriseSetEnterpriseAllAlertRecipients - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'enterpriseId': 'int',
            'enterpriseUsers': 'list[EnterprisesetEnterpriseAllAlertsRecipientsEnterpriseUsers]',
            'smsEnabled': 'bool',
            'smsList': 'list[list[object]]',
            'emailEnabled': 'bool',
            'emailList': 'list[str]',
            'mobileEnabled': 'bool',
            'mobileList': 'list[str]'
        }

        self.attribute_map = {
            'enterpriseId': 'enterpriseId',
            'enterpriseUsers': 'enterpriseUsers',
            'smsEnabled': 'smsEnabled',
            'smsList': 'smsList',
            'emailEnabled': 'emailEnabled',
            'emailList': 'emailList',
            'mobileEnabled': 'mobileEnabled',
            'mobileList': 'mobileList'
        }

        self._enterpriseId = enterpriseId
        self._enterpriseUsers = enterpriseUsers
        self._smsEnabled = smsEnabled
        self._smsList = smsList
        self._emailEnabled = emailEnabled
        self._emailList = emailList
        self._mobileEnabled = mobileEnabled
        self._mobileList = mobileList

    @property
    def enterpriseId(self):
        """
        Gets the enterpriseId of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The enterpriseId of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: int
        """
        return self._enterpriseId

    @enterpriseId.setter
    def enterpriseId(self, enterpriseId):
        """
        Sets the enterpriseId of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param enterpriseId: The enterpriseId of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: int
        """

        self._enterpriseId = enterpriseId

    @property
    def enterpriseUsers(self):
        """
        Gets the enterpriseUsers of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The enterpriseUsers of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: list[EnterprisesetEnterpriseAllAlertsRecipientsEnterpriseUsers]
        """
        return self._enterpriseUsers

    @enterpriseUsers.setter
    def enterpriseUsers(self, enterpriseUsers):
        """
        Sets the enterpriseUsers of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param enterpriseUsers: The enterpriseUsers of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: list[EnterprisesetEnterpriseAllAlertsRecipientsEnterpriseUsers]
        """

        self._enterpriseUsers = enterpriseUsers

    @property
    def smsEnabled(self):
        """
        Gets the smsEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The smsEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: bool
        """
        return self._smsEnabled

    @smsEnabled.setter
    def smsEnabled(self, smsEnabled):
        """
        Sets the smsEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param smsEnabled: The smsEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: bool
        """

        self._smsEnabled = smsEnabled

    @property
    def smsList(self):
        """
        Gets the smsList of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The smsList of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: list[list[object]]
        """
        return self._smsList

    @smsList.setter
    def smsList(self, smsList):
        """
        Sets the smsList of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param smsList: The smsList of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: list[list[object]]
        """

        self._smsList = smsList

    @property
    def emailEnabled(self):
        """
        Gets the emailEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The emailEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: bool
        """
        return self._emailEnabled

    @emailEnabled.setter
    def emailEnabled(self, emailEnabled):
        """
        Sets the emailEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param emailEnabled: The emailEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: bool
        """

        self._emailEnabled = emailEnabled

    @property
    def emailList(self):
        """
        Gets the emailList of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The emailList of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: list[str]
        """
        return self._emailList

    @emailList.setter
    def emailList(self, emailList):
        """
        Sets the emailList of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param emailList: The emailList of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: list[str]
        """

        self._emailList = emailList

    @property
    def mobileEnabled(self):
        """
        Gets the mobileEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The mobileEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: bool
        """
        return self._mobileEnabled

    @mobileEnabled.setter
    def mobileEnabled(self, mobileEnabled):
        """
        Sets the mobileEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param mobileEnabled: The mobileEnabled of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: bool
        """

        self._mobileEnabled = mobileEnabled

    @property
    def mobileList(self):
        """
        Gets the mobileList of this EnterpriseSetEnterpriseAllAlertRecipients.

        :return: The mobileList of this EnterpriseSetEnterpriseAllAlertRecipients.
        :rtype: list[str]
        """
        return self._mobileList

    @mobileList.setter
    def mobileList(self, mobileList):
        """
        Sets the mobileList of this EnterpriseSetEnterpriseAllAlertRecipients.

        :param mobileList: The mobileList of this EnterpriseSetEnterpriseAllAlertRecipients.
        :type: list[str]
        """

        self._mobileList = mobileList

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EnterpriseSetEnterpriseAllAlertRecipients):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
