# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FlowMetricTimeSeriesItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, data=None, max=None, metric=None, min=None, startTime=None, tickInterval=None, total=None):
        """
        FlowMetricTimeSeriesItem - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'data': 'list[int]',
            'max': 'int',
            'metric': 'BasicMetric',
            'min': 'int',
            'startTime': 'datetime',
            'tickInterval': 'int',
            'total': 'int'
        }

        self.attribute_map = {
            'data': 'data',
            'max': 'max',
            'metric': 'metric',
            'min': 'min',
            'startTime': 'startTime',
            'tickInterval': 'tickInterval',
            'total': 'total'
        }

        self._data = data
        self._max = max
        self._metric = metric
        self._min = min
        self._startTime = startTime
        self._tickInterval = tickInterval
        self._total = total

    @property
    def data(self):
        """
        Gets the data of this FlowMetricTimeSeriesItem.

        :return: The data of this FlowMetricTimeSeriesItem.
        :rtype: list[int]
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this FlowMetricTimeSeriesItem.

        :param data: The data of this FlowMetricTimeSeriesItem.
        :type: list[int]
        """

        self._data = data

    @property
    def max(self):
        """
        Gets the max of this FlowMetricTimeSeriesItem.

        :return: The max of this FlowMetricTimeSeriesItem.
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max):
        """
        Sets the max of this FlowMetricTimeSeriesItem.

        :param max: The max of this FlowMetricTimeSeriesItem.
        :type: int
        """

        self._max = max

    @property
    def metric(self):
        """
        Gets the metric of this FlowMetricTimeSeriesItem.

        :return: The metric of this FlowMetricTimeSeriesItem.
        :rtype: BasicMetric
        """
        return self._metric

    @metric.setter
    def metric(self, metric):
        """
        Sets the metric of this FlowMetricTimeSeriesItem.

        :param metric: The metric of this FlowMetricTimeSeriesItem.
        :type: BasicMetric
        """

        self._metric = metric

    @property
    def min(self):
        """
        Gets the min of this FlowMetricTimeSeriesItem.

        :return: The min of this FlowMetricTimeSeriesItem.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min):
        """
        Sets the min of this FlowMetricTimeSeriesItem.

        :param min: The min of this FlowMetricTimeSeriesItem.
        :type: int
        """

        self._min = min

    @property
    def startTime(self):
        """
        Gets the startTime of this FlowMetricTimeSeriesItem.

        :return: The startTime of this FlowMetricTimeSeriesItem.
        :rtype: datetime
        """
        return self._startTime

    @startTime.setter
    def startTime(self, startTime):
        """
        Sets the startTime of this FlowMetricTimeSeriesItem.

        :param startTime: The startTime of this FlowMetricTimeSeriesItem.
        :type: datetime
        """

        self._startTime = startTime

    @property
    def tickInterval(self):
        """
        Gets the tickInterval of this FlowMetricTimeSeriesItem.

        :return: The tickInterval of this FlowMetricTimeSeriesItem.
        :rtype: int
        """
        return self._tickInterval

    @tickInterval.setter
    def tickInterval(self, tickInterval):
        """
        Sets the tickInterval of this FlowMetricTimeSeriesItem.

        :param tickInterval: The tickInterval of this FlowMetricTimeSeriesItem.
        :type: int
        """

        self._tickInterval = tickInterval

    @property
    def total(self):
        """
        Gets the total of this FlowMetricTimeSeriesItem.

        :return: The total of this FlowMetricTimeSeriesItem.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this FlowMetricTimeSeriesItem.

        :param total: The total of this FlowMetricTimeSeriesItem.
        :type: int
        """

        self._total = total

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FlowMetricTimeSeriesItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
