# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GatewayRole(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, created=None, gatewayId=None, gatewayRole=None, required=None):
        """
        GatewayRole - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'created': 'datetime',
            'gatewayId': 'int',
            'gatewayRole': 'str',
            'required': 'int'
        }

        self.attribute_map = {
            'created': 'created',
            'gatewayId': 'gatewayId',
            'gatewayRole': 'gatewayRole',
            'required': 'required'
        }

        self._created = created
        self._gatewayId = gatewayId
        self._gatewayRole = gatewayRole
        self._required = required

    @property
    def created(self):
        """
        Gets the created of this GatewayRole.

        :return: The created of this GatewayRole.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this GatewayRole.

        :param created: The created of this GatewayRole.
        :type: datetime
        """

        self._created = created

    @property
    def gatewayId(self):
        """
        Gets the gatewayId of this GatewayRole.

        :return: The gatewayId of this GatewayRole.
        :rtype: int
        """
        return self._gatewayId

    @gatewayId.setter
    def gatewayId(self, gatewayId):
        """
        Sets the gatewayId of this GatewayRole.

        :param gatewayId: The gatewayId of this GatewayRole.
        :type: int
        """

        self._gatewayId = gatewayId

    @property
    def gatewayRole(self):
        """
        Gets the gatewayRole of this GatewayRole.

        :return: The gatewayRole of this GatewayRole.
        :rtype: str
        """
        return self._gatewayRole

    @gatewayRole.setter
    def gatewayRole(self, gatewayRole):
        """
        Sets the gatewayRole of this GatewayRole.

        :param gatewayRole: The gatewayRole of this GatewayRole.
        :type: str
        """

        self._gatewayRole = gatewayRole

    @property
    def required(self):
        """
        Gets the required of this GatewayRole.

        :return: The required of this GatewayRole.
        :rtype: int
        """
        return self._required

    @required.setter
    def required(self, required):
        """
        Sets the required of this GatewayRole.

        :param required: The required of this GatewayRole.
        :type: int
        """

        self._required = required

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GatewayRole):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
