# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InventoryItemEdge(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, edge=None, site=None):
        """
        InventoryItemEdge - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'edge': 'str',
            'site': 'InventoryItemEdgeSite'
        }

        self.attribute_map = {
            'id': 'id',
            'edge': 'edge',
            'site': 'site'
        }

        self._id = id
        self._edge = edge
        self._site = site

    @property
    def id(self):
        """
        Gets the id of this InventoryItemEdge.

        :return: The id of this InventoryItemEdge.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this InventoryItemEdge.

        :param id: The id of this InventoryItemEdge.
        :type: int
        """

        self._id = id

    @property
    def edge(self):
        """
        Gets the edge of this InventoryItemEdge.

        :return: The edge of this InventoryItemEdge.
        :rtype: str
        """
        return self._edge

    @edge.setter
    def edge(self, edge):
        """
        Sets the edge of this InventoryItemEdge.

        :param edge: The edge of this InventoryItemEdge.
        :type: str
        """

        self._edge = edge

    @property
    def site(self):
        """
        Gets the site of this InventoryItemEdge.

        :return: The site of this InventoryItemEdge.
        :rtype: InventoryItemEdgeSite
        """
        return self._site

    @site.setter
    def site(self, site):
        """
        Sets the site of this InventoryItemEdge.

        :param site: The site of this InventoryItemEdge.
        :type: InventoryItemEdgeSite
        """

        self._site = site

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InventoryItemEdge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
