# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class IpPortMapping(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, subnets=None, tcpPorts=None, udpPorts=None):
        """
        IpPortMapping - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'subnets': 'list[str]',
            'tcpPorts': 'list[int]',
            'udpPorts': 'list[int]'
        }

        self.attribute_map = {
            'subnets': 'subnets',
            'tcpPorts': 'tcpPorts',
            'udpPorts': 'udpPorts'
        }

        self._subnets = subnets
        self._tcpPorts = tcpPorts
        self._udpPorts = udpPorts

    @property
    def subnets(self):
        """
        Gets the subnets of this IpPortMapping.

        :return: The subnets of this IpPortMapping.
        :rtype: list[str]
        """
        return self._subnets

    @subnets.setter
    def subnets(self, subnets):
        """
        Sets the subnets of this IpPortMapping.

        :param subnets: The subnets of this IpPortMapping.
        :type: list[str]
        """

        self._subnets = subnets

    @property
    def tcpPorts(self):
        """
        Gets the tcpPorts of this IpPortMapping.

        :return: The tcpPorts of this IpPortMapping.
        :rtype: list[int]
        """
        return self._tcpPorts

    @tcpPorts.setter
    def tcpPorts(self, tcpPorts):
        """
        Sets the tcpPorts of this IpPortMapping.

        :param tcpPorts: The tcpPorts of this IpPortMapping.
        :type: list[int]
        """

        self._tcpPorts = tcpPorts

    @property
    def udpPorts(self):
        """
        Gets the udpPorts of this IpPortMapping.

        :return: The udpPorts of this IpPortMapping.
        :rtype: list[int]
        """
        return self._udpPorts

    @udpPorts.setter
    def udpPorts(self, udpPorts):
        """
        Sets the udpPorts of this IpPortMapping.

        :param udpPorts: The udpPorts of this IpPortMapping.
        :type: list[int]
        """

        self._udpPorts = udpPorts

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, IpPortMapping):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
