# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class LinkQualityObjectTimeseriesData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, before=None, after=None, metadata=None, timestamp=None):
        """
        LinkQualityObjectTimeseriesData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'before': 'dict(str, int)',
            'after': 'dict(str, int)',
            'metadata': 'LinkQualityObjectTimeseriesDataMetadata',
            'timestamp': 'int'
        }

        self.attribute_map = {
            'before': 'before',
            'after': 'after',
            'metadata': 'metadata',
            'timestamp': 'timestamp'
        }

        self._before = before
        self._after = after
        self._metadata = metadata
        self._timestamp = timestamp

    @property
    def before(self):
        """
        Gets the before of this LinkQualityObjectTimeseriesData.

        :return: The before of this LinkQualityObjectTimeseriesData.
        :rtype: dict(str, int)
        """
        return self._before

    @before.setter
    def before(self, before):
        """
        Sets the before of this LinkQualityObjectTimeseriesData.

        :param before: The before of this LinkQualityObjectTimeseriesData.
        :type: dict(str, int)
        """

        self._before = before

    @property
    def after(self):
        """
        Gets the after of this LinkQualityObjectTimeseriesData.

        :return: The after of this LinkQualityObjectTimeseriesData.
        :rtype: dict(str, int)
        """
        return self._after

    @after.setter
    def after(self, after):
        """
        Sets the after of this LinkQualityObjectTimeseriesData.

        :param after: The after of this LinkQualityObjectTimeseriesData.
        :type: dict(str, int)
        """

        self._after = after

    @property
    def metadata(self):
        """
        Gets the metadata of this LinkQualityObjectTimeseriesData.

        :return: The metadata of this LinkQualityObjectTimeseriesData.
        :rtype: LinkQualityObjectTimeseriesDataMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """
        Sets the metadata of this LinkQualityObjectTimeseriesData.

        :param metadata: The metadata of this LinkQualityObjectTimeseriesData.
        :type: LinkQualityObjectTimeseriesDataMetadata
        """

        self._metadata = metadata

    @property
    def timestamp(self):
        """
        Gets the timestamp of this LinkQualityObjectTimeseriesData.

        :return: The timestamp of this LinkQualityObjectTimeseriesData.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this LinkQualityObjectTimeseriesData.

        :param timestamp: The timestamp of this LinkQualityObjectTimeseriesData.
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, LinkQualityObjectTimeseriesData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
