# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MetricsGetEdgeCategoryMetrics(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, enterpriseId=None, interval=None, metrics=None, sort=None, limit=None, categories=None):
        """
        MetricsGetEdgeCategoryMetrics - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'enterpriseId': 'int',
            'interval': 'Interval',
            'metrics': 'BasicMetrics',
            'sort': 'BasicMetric',
            'limit': 'int',
            'categories': 'list[int]'
        }

        self.attribute_map = {
            'id': 'id',
            'enterpriseId': 'enterpriseId',
            'interval': 'interval',
            'metrics': 'metrics',
            'sort': 'sort',
            'limit': 'limit',
            'categories': 'categories'
        }

        self._id = id
        self._enterpriseId = enterpriseId
        self._interval = interval
        self._metrics = metrics
        self._sort = sort
        self._limit = limit
        self._categories = categories

    @property
    def id(self):
        """
        Gets the id of this MetricsGetEdgeCategoryMetrics.

        :return: The id of this MetricsGetEdgeCategoryMetrics.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this MetricsGetEdgeCategoryMetrics.

        :param id: The id of this MetricsGetEdgeCategoryMetrics.
        :type: int
        """

        self._id = id

    @property
    def enterpriseId(self):
        """
        Gets the enterpriseId of this MetricsGetEdgeCategoryMetrics.

        :return: The enterpriseId of this MetricsGetEdgeCategoryMetrics.
        :rtype: int
        """
        return self._enterpriseId

    @enterpriseId.setter
    def enterpriseId(self, enterpriseId):
        """
        Sets the enterpriseId of this MetricsGetEdgeCategoryMetrics.

        :param enterpriseId: The enterpriseId of this MetricsGetEdgeCategoryMetrics.
        :type: int
        """

        self._enterpriseId = enterpriseId

    @property
    def interval(self):
        """
        Gets the interval of this MetricsGetEdgeCategoryMetrics.

        :return: The interval of this MetricsGetEdgeCategoryMetrics.
        :rtype: Interval
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """
        Sets the interval of this MetricsGetEdgeCategoryMetrics.

        :param interval: The interval of this MetricsGetEdgeCategoryMetrics.
        :type: Interval
        """

        self._interval = interval

    @property
    def metrics(self):
        """
        Gets the metrics of this MetricsGetEdgeCategoryMetrics.

        :return: The metrics of this MetricsGetEdgeCategoryMetrics.
        :rtype: BasicMetrics
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """
        Sets the metrics of this MetricsGetEdgeCategoryMetrics.

        :param metrics: The metrics of this MetricsGetEdgeCategoryMetrics.
        :type: BasicMetrics
        """

        self._metrics = metrics

    @property
    def sort(self):
        """
        Gets the sort of this MetricsGetEdgeCategoryMetrics.

        :return: The sort of this MetricsGetEdgeCategoryMetrics.
        :rtype: BasicMetric
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """
        Sets the sort of this MetricsGetEdgeCategoryMetrics.

        :param sort: The sort of this MetricsGetEdgeCategoryMetrics.
        :type: BasicMetric
        """

        self._sort = sort

    @property
    def limit(self):
        """
        Gets the limit of this MetricsGetEdgeCategoryMetrics.

        :return: The limit of this MetricsGetEdgeCategoryMetrics.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """
        Sets the limit of this MetricsGetEdgeCategoryMetrics.

        :param limit: The limit of this MetricsGetEdgeCategoryMetrics.
        :type: int
        """

        self._limit = limit

    @property
    def categories(self):
        """
        Gets the categories of this MetricsGetEdgeCategoryMetrics.

        :return: The categories of this MetricsGetEdgeCategoryMetrics.
        :rtype: list[int]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this MetricsGetEdgeCategoryMetrics.

        :param categories: The categories of this MetricsGetEdgeCategoryMetrics.
        :type: list[int]
        """

        self._categories = categories

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MetricsGetEdgeCategoryMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
