# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MetricsGetEdgeAppLinkSeries(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, enterpriseId=None, interval=None, metrics=None, links=None):
        """
        MetricsGetEdgeAppLinkSeries - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'enterpriseId': 'int',
            'interval': 'Interval',
            'metrics': 'BasicMetrics',
            'links': 'list[int]'
        }

        self.attribute_map = {
            'id': 'id',
            'enterpriseId': 'enterpriseId',
            'interval': 'interval',
            'metrics': 'metrics',
            'links': 'links'
        }

        self._id = id
        self._enterpriseId = enterpriseId
        self._interval = interval
        self._metrics = metrics
        self._links = links

    @property
    def id(self):
        """
        Gets the id of this MetricsGetEdgeAppLinkSeries.

        :return: The id of this MetricsGetEdgeAppLinkSeries.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this MetricsGetEdgeAppLinkSeries.

        :param id: The id of this MetricsGetEdgeAppLinkSeries.
        :type: int
        """

        self._id = id

    @property
    def enterpriseId(self):
        """
        Gets the enterpriseId of this MetricsGetEdgeAppLinkSeries.

        :return: The enterpriseId of this MetricsGetEdgeAppLinkSeries.
        :rtype: int
        """
        return self._enterpriseId

    @enterpriseId.setter
    def enterpriseId(self, enterpriseId):
        """
        Sets the enterpriseId of this MetricsGetEdgeAppLinkSeries.

        :param enterpriseId: The enterpriseId of this MetricsGetEdgeAppLinkSeries.
        :type: int
        """

        self._enterpriseId = enterpriseId

    @property
    def interval(self):
        """
        Gets the interval of this MetricsGetEdgeAppLinkSeries.

        :return: The interval of this MetricsGetEdgeAppLinkSeries.
        :rtype: Interval
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """
        Sets the interval of this MetricsGetEdgeAppLinkSeries.

        :param interval: The interval of this MetricsGetEdgeAppLinkSeries.
        :type: Interval
        """

        self._interval = interval

    @property
    def metrics(self):
        """
        Gets the metrics of this MetricsGetEdgeAppLinkSeries.

        :return: The metrics of this MetricsGetEdgeAppLinkSeries.
        :rtype: BasicMetrics
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """
        Sets the metrics of this MetricsGetEdgeAppLinkSeries.

        :param metrics: The metrics of this MetricsGetEdgeAppLinkSeries.
        :type: BasicMetrics
        """

        self._metrics = metrics

    @property
    def links(self):
        """
        Gets the links of this MetricsGetEdgeAppLinkSeries.

        :return: The links of this MetricsGetEdgeAppLinkSeries.
        :rtype: list[int]
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this MetricsGetEdgeAppLinkSeries.

        :param links: The links of this MetricsGetEdgeAppLinkSeries.
        :type: list[int]
        """

        self._links = links

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MetricsGetEdgeAppLinkSeries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
