# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ModelConfiguration(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, created=None, description=None, edgeCount=None, effective=None, id=None, modified=None, modules=None, name=None, version=None):
        """
        ModelConfiguration - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'created': 'str',
            'description': 'str',
            'edgeCount': 'int',
            'effective': 'str',
            'id': 'int',
            'modified': 'str',
            'modules': 'list[ConfigurationModule]',
            'name': 'str',
            'version': 'str'
        }

        self.attribute_map = {
            'created': 'created',
            'description': 'description',
            'edgeCount': 'edgeCount',
            'effective': 'effective',
            'id': 'id',
            'modified': 'modified',
            'modules': 'modules',
            'name': 'name',
            'version': 'version'
        }

        self._created = created
        self._description = description
        self._edgeCount = edgeCount
        self._effective = effective
        self._id = id
        self._modified = modified
        self._modules = modules
        self._name = name
        self._version = version

    @property
    def created(self):
        """
        Gets the created of this ModelConfiguration.

        :return: The created of this ModelConfiguration.
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this ModelConfiguration.

        :param created: The created of this ModelConfiguration.
        :type: str
        """

        self._created = created

    @property
    def description(self):
        """
        Gets the description of this ModelConfiguration.

        :return: The description of this ModelConfiguration.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this ModelConfiguration.

        :param description: The description of this ModelConfiguration.
        :type: str
        """

        self._description = description

    @property
    def edgeCount(self):
        """
        Gets the edgeCount of this ModelConfiguration.

        :return: The edgeCount of this ModelConfiguration.
        :rtype: int
        """
        return self._edgeCount

    @edgeCount.setter
    def edgeCount(self, edgeCount):
        """
        Sets the edgeCount of this ModelConfiguration.

        :param edgeCount: The edgeCount of this ModelConfiguration.
        :type: int
        """

        self._edgeCount = edgeCount

    @property
    def effective(self):
        """
        Gets the effective of this ModelConfiguration.

        :return: The effective of this ModelConfiguration.
        :rtype: str
        """
        return self._effective

    @effective.setter
    def effective(self, effective):
        """
        Sets the effective of this ModelConfiguration.

        :param effective: The effective of this ModelConfiguration.
        :type: str
        """

        self._effective = effective

    @property
    def id(self):
        """
        Gets the id of this ModelConfiguration.

        :return: The id of this ModelConfiguration.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ModelConfiguration.

        :param id: The id of this ModelConfiguration.
        :type: int
        """

        self._id = id

    @property
    def modified(self):
        """
        Gets the modified of this ModelConfiguration.

        :return: The modified of this ModelConfiguration.
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """
        Sets the modified of this ModelConfiguration.

        :param modified: The modified of this ModelConfiguration.
        :type: str
        """

        self._modified = modified

    @property
    def modules(self):
        """
        Gets the modules of this ModelConfiguration.

        :return: The modules of this ModelConfiguration.
        :rtype: list[ConfigurationModule]
        """
        return self._modules

    @modules.setter
    def modules(self, modules):
        """
        Sets the modules of this ModelConfiguration.

        :param modules: The modules of this ModelConfiguration.
        :type: list[ConfigurationModule]
        """

        self._modules = modules

    @property
    def name(self):
        """
        Gets the name of this ModelConfiguration.

        :return: The name of this ModelConfiguration.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ModelConfiguration.

        :param name: The name of this ModelConfiguration.
        :type: str
        """

        self._name = name

    @property
    def version(self):
        """
        Gets the version of this ModelConfiguration.

        :return: The version of this ModelConfiguration.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this ModelConfiguration.

        :param version: The version of this ModelConfiguration.
        :type: str
        """

        self._version = version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ModelConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
