# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RoleDeleteRoleCustomization(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, forRoleId=None, name=None, userId=None, enterpriseId=None, operatorId=None, networkId=None):
        """
        RoleDeleteRoleCustomization - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'forRoleId': 'int',
            'name': 'str',
            'userId': 'int',
            'enterpriseId': 'int',
            'operatorId': 'int',
            'networkId': 'int'
        }

        self.attribute_map = {
            'forRoleId': 'forRoleId',
            'name': 'name',
            'userId': 'userId',
            'enterpriseId': 'enterpriseId',
            'operatorId': 'operatorId',
            'networkId': 'networkId'
        }

        self._forRoleId = forRoleId
        self._name = name
        self._userId = userId
        self._enterpriseId = enterpriseId
        self._operatorId = operatorId
        self._networkId = networkId

    @property
    def forRoleId(self):
        """
        Gets the forRoleId of this RoleDeleteRoleCustomization.

        :return: The forRoleId of this RoleDeleteRoleCustomization.
        :rtype: int
        """
        return self._forRoleId

    @forRoleId.setter
    def forRoleId(self, forRoleId):
        """
        Sets the forRoleId of this RoleDeleteRoleCustomization.

        :param forRoleId: The forRoleId of this RoleDeleteRoleCustomization.
        :type: int
        """

        self._forRoleId = forRoleId

    @property
    def name(self):
        """
        Gets the name of this RoleDeleteRoleCustomization.

        :return: The name of this RoleDeleteRoleCustomization.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this RoleDeleteRoleCustomization.

        :param name: The name of this RoleDeleteRoleCustomization.
        :type: str
        """

        self._name = name

    @property
    def userId(self):
        """
        Gets the userId of this RoleDeleteRoleCustomization.

        :return: The userId of this RoleDeleteRoleCustomization.
        :rtype: int
        """
        return self._userId

    @userId.setter
    def userId(self, userId):
        """
        Sets the userId of this RoleDeleteRoleCustomization.

        :param userId: The userId of this RoleDeleteRoleCustomization.
        :type: int
        """

        self._userId = userId

    @property
    def enterpriseId(self):
        """
        Gets the enterpriseId of this RoleDeleteRoleCustomization.

        :return: The enterpriseId of this RoleDeleteRoleCustomization.
        :rtype: int
        """
        return self._enterpriseId

    @enterpriseId.setter
    def enterpriseId(self, enterpriseId):
        """
        Sets the enterpriseId of this RoleDeleteRoleCustomization.

        :param enterpriseId: The enterpriseId of this RoleDeleteRoleCustomization.
        :type: int
        """

        self._enterpriseId = enterpriseId

    @property
    def operatorId(self):
        """
        Gets the operatorId of this RoleDeleteRoleCustomization.

        :return: The operatorId of this RoleDeleteRoleCustomization.
        :rtype: int
        """
        return self._operatorId

    @operatorId.setter
    def operatorId(self, operatorId):
        """
        Sets the operatorId of this RoleDeleteRoleCustomization.

        :param operatorId: The operatorId of this RoleDeleteRoleCustomization.
        :type: int
        """

        self._operatorId = operatorId

    @property
    def networkId(self):
        """
        Gets the networkId of this RoleDeleteRoleCustomization.

        :return: The networkId of this RoleDeleteRoleCustomization.
        :rtype: int
        """
        return self._networkId

    @networkId.setter
    def networkId(self, networkId):
        """
        Sets the networkId of this RoleDeleteRoleCustomization.

        :param networkId: The networkId of this RoleDeleteRoleCustomization.
        :type: int
        """

        self._networkId = networkId

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RoleDeleteRoleCustomization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
