# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Role(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, created=None, operatorId=None, networkId=None, enterpriseId=None, enterpriseProxyId=None, name=None, userType=None, fromUserType=None, isSuper=None, description=None, precedence=None, modified=None):
        """
        Role - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'created': 'datetime',
            'operatorId': 'int',
            'networkId': 'int',
            'enterpriseId': 'int',
            'enterpriseProxyId': 'int',
            'name': 'str',
            'userType': 'str',
            'fromUserType': 'str',
            'isSuper': 'int',
            'description': 'str',
            'precedence': 'int',
            'modified': 'datetime'
        }

        self.attribute_map = {
            'id': 'id',
            'created': 'created',
            'operatorId': 'operatorId',
            'networkId': 'networkId',
            'enterpriseId': 'enterpriseId',
            'enterpriseProxyId': 'enterpriseProxyId',
            'name': 'name',
            'userType': 'userType',
            'fromUserType': 'fromUserType',
            'isSuper': 'isSuper',
            'description': 'description',
            'precedence': 'precedence',
            'modified': 'modified'
        }

        self._id = id
        self._created = created
        self._operatorId = operatorId
        self._networkId = networkId
        self._enterpriseId = enterpriseId
        self._enterpriseProxyId = enterpriseProxyId
        self._name = name
        self._userType = userType
        self._fromUserType = fromUserType
        self._isSuper = isSuper
        self._description = description
        self._precedence = precedence
        self._modified = modified

    @property
    def id(self):
        """
        Gets the id of this Role.

        :return: The id of this Role.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Role.

        :param id: The id of this Role.
        :type: int
        """

        self._id = id

    @property
    def created(self):
        """
        Gets the created of this Role.

        :return: The created of this Role.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this Role.

        :param created: The created of this Role.
        :type: datetime
        """

        self._created = created

    @property
    def operatorId(self):
        """
        Gets the operatorId of this Role.

        :return: The operatorId of this Role.
        :rtype: int
        """
        return self._operatorId

    @operatorId.setter
    def operatorId(self, operatorId):
        """
        Sets the operatorId of this Role.

        :param operatorId: The operatorId of this Role.
        :type: int
        """

        self._operatorId = operatorId

    @property
    def networkId(self):
        """
        Gets the networkId of this Role.

        :return: The networkId of this Role.
        :rtype: int
        """
        return self._networkId

    @networkId.setter
    def networkId(self, networkId):
        """
        Sets the networkId of this Role.

        :param networkId: The networkId of this Role.
        :type: int
        """

        self._networkId = networkId

    @property
    def enterpriseId(self):
        """
        Gets the enterpriseId of this Role.

        :return: The enterpriseId of this Role.
        :rtype: int
        """
        return self._enterpriseId

    @enterpriseId.setter
    def enterpriseId(self, enterpriseId):
        """
        Sets the enterpriseId of this Role.

        :param enterpriseId: The enterpriseId of this Role.
        :type: int
        """

        self._enterpriseId = enterpriseId

    @property
    def enterpriseProxyId(self):
        """
        Gets the enterpriseProxyId of this Role.

        :return: The enterpriseProxyId of this Role.
        :rtype: int
        """
        return self._enterpriseProxyId

    @enterpriseProxyId.setter
    def enterpriseProxyId(self, enterpriseProxyId):
        """
        Sets the enterpriseProxyId of this Role.

        :param enterpriseProxyId: The enterpriseProxyId of this Role.
        :type: int
        """

        self._enterpriseProxyId = enterpriseProxyId

    @property
    def name(self):
        """
        Gets the name of this Role.

        :return: The name of this Role.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Role.

        :param name: The name of this Role.
        :type: str
        """

        self._name = name

    @property
    def userType(self):
        """
        Gets the userType of this Role.

        :return: The userType of this Role.
        :rtype: str
        """
        return self._userType

    @userType.setter
    def userType(self, userType):
        """
        Sets the userType of this Role.

        :param userType: The userType of this Role.
        :type: str
        """

        self._userType = userType

    @property
    def fromUserType(self):
        """
        Gets the fromUserType of this Role.

        :return: The fromUserType of this Role.
        :rtype: str
        """
        return self._fromUserType

    @fromUserType.setter
    def fromUserType(self, fromUserType):
        """
        Sets the fromUserType of this Role.

        :param fromUserType: The fromUserType of this Role.
        :type: str
        """

        self._fromUserType = fromUserType

    @property
    def isSuper(self):
        """
        Gets the isSuper of this Role.

        :return: The isSuper of this Role.
        :rtype: int
        """
        return self._isSuper

    @isSuper.setter
    def isSuper(self, isSuper):
        """
        Sets the isSuper of this Role.

        :param isSuper: The isSuper of this Role.
        :type: int
        """

        self._isSuper = isSuper

    @property
    def description(self):
        """
        Gets the description of this Role.

        :return: The description of this Role.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Role.

        :param description: The description of this Role.
        :type: str
        """

        self._description = description

    @property
    def precedence(self):
        """
        Gets the precedence of this Role.

        :return: The precedence of this Role.
        :rtype: int
        """
        return self._precedence

    @precedence.setter
    def precedence(self, precedence):
        """
        Sets the precedence of this Role.

        :param precedence: The precedence of this Role.
        :type: int
        """

        self._precedence = precedence

    @property
    def modified(self):
        """
        Gets the modified of this Role.

        :return: The modified of this Role.
        :rtype: datetime
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """
        Sets the modified of this Role.

        :param modified: The modified of this Role.
        :type: datetime
        """

        self._modified = modified

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Role):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
