# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SegmentData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, segmentId=None, delegateToEnterprise=None, delegateToEnterpriseProxy=None):
        """
        SegmentData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'segmentId': 'int',
            'delegateToEnterprise': 'bool',
            'delegateToEnterpriseProxy': 'bool'
        }

        self.attribute_map = {
            'segmentId': 'segmentId',
            'delegateToEnterprise': 'delegateToEnterprise',
            'delegateToEnterpriseProxy': 'delegateToEnterpriseProxy'
        }

        self._segmentId = segmentId
        self._delegateToEnterprise = delegateToEnterprise
        self._delegateToEnterpriseProxy = delegateToEnterpriseProxy

    @property
    def segmentId(self):
        """
        Gets the segmentId of this SegmentData.

        :return: The segmentId of this SegmentData.
        :rtype: int
        """
        return self._segmentId

    @segmentId.setter
    def segmentId(self, segmentId):
        """
        Sets the segmentId of this SegmentData.

        :param segmentId: The segmentId of this SegmentData.
        :type: int
        """

        self._segmentId = segmentId

    @property
    def delegateToEnterprise(self):
        """
        Gets the delegateToEnterprise of this SegmentData.

        :return: The delegateToEnterprise of this SegmentData.
        :rtype: bool
        """
        return self._delegateToEnterprise

    @delegateToEnterprise.setter
    def delegateToEnterprise(self, delegateToEnterprise):
        """
        Sets the delegateToEnterprise of this SegmentData.

        :param delegateToEnterprise: The delegateToEnterprise of this SegmentData.
        :type: bool
        """

        self._delegateToEnterprise = delegateToEnterprise

    @property
    def delegateToEnterpriseProxy(self):
        """
        Gets the delegateToEnterpriseProxy of this SegmentData.

        :return: The delegateToEnterpriseProxy of this SegmentData.
        :rtype: bool
        """
        return self._delegateToEnterpriseProxy

    @delegateToEnterpriseProxy.setter
    def delegateToEnterpriseProxy(self, delegateToEnterpriseProxy):
        """
        Sets the delegateToEnterpriseProxy of this SegmentData.

        :param delegateToEnterpriseProxy: The delegateToEnterpriseProxy of this SegmentData.
        :type: bool
        """

        self._delegateToEnterpriseProxy = delegateToEnterpriseProxy

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SegmentData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
