# coding: utf-8

"""
    Velocloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.2.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Vlan(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, vlanId=None, staticReserved=None):
        """
        Vlan - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'vlanId': 'int',
            'staticReserved': 'int'
        }

        self.attribute_map = {
            'name': 'name',
            'vlanId': 'vlanId',
            'staticReserved': 'staticReserved'
        }

        self._name = name
        self._vlanId = vlanId
        self._staticReserved = staticReserved

    @property
    def name(self):
        """
        Gets the name of this Vlan.

        :return: The name of this Vlan.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Vlan.

        :param name: The name of this Vlan.
        :type: str
        """

        self._name = name

    @property
    def vlanId(self):
        """
        Gets the vlanId of this Vlan.

        :return: The vlanId of this Vlan.
        :rtype: int
        """
        return self._vlanId

    @vlanId.setter
    def vlanId(self, vlanId):
        """
        Sets the vlanId of this Vlan.

        :param vlanId: The vlanId of this Vlan.
        :type: int
        """

        self._vlanId = vlanId

    @property
    def staticReserved(self):
        """
        Gets the staticReserved of this Vlan.

        :return: The staticReserved of this Vlan.
        :rtype: int
        """
        return self._staticReserved

    @staticReserved.setter
    def staticReserved(self, staticReserved):
        """
        Sets the staticReserved of this Vlan.

        :param staticReserved: The staticReserved of this Vlan.
        :type: int
        """

        self._staticReserved = staticReserved

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Vlan):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
