{
 "title": "Dummy",
 "time": { "from": "now-25m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Edge States ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (state) ((edge_state_gauge{enterprise_name='$enterprise'})) ",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Link States ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (state) ((link_state_gauge{enterprise_name='$enterprise'})) ",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Edge States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (state) ((edge_state_gauge{enterprise_name='$enterprise'})) ",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Link States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) ((link_state_gauge{enterprise_name='$enterprise'}))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Sites not online",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (enterprise_name) (edge_state_gauge{state='OFFLINE', enterprise_name='$enterprise'})"
    },
    {
     "expr": "sum by (enterprise_name) (edge_state_gauge{state='NEVER_ACTIVATED', enterprise_name='$enterprise'})"
    },
    {
     "expr": "sum by (enterprise_name) (edge_state_gauge{state='DEGRADED', enterprise_name='$enterprise'})"
    },
    {
     "expr": "sum by (enterprise_name) (edge_state_gauge{state=~'OFFLINE|DEGRADED|NEVER_ACTIVATED', enterprise_name='$enterprise'})"
    }
   ]
  },
  {
   "title": "Link States",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (enterprise_name) (link_state_gauge{state='STABLE', enterprise_name='$enterprise'}) "
    },
    {
     "expr": "sum by (enterprise_name) (link_state_gauge{state='UNSTABLE', enterprise_name='$enterprise'})"
    },
    {
     "expr": "sum by (enterprise_name) (link_state_gauge{state='DISCONNECTED', enterprise_name='$enterprise'}) "
    },
    {
     "expr": "sum by (enterprise_name) (link_state_gauge{enterprise_name='$enterprise'}) ",
     "legendFormat": "{{enterprise_name}}:{{state}}"
    }
   ]
  }
 ]
}