{
 "title": "Triage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total tickets monitored in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(tickets_with_triage_counter_total{job=\"service-outage-monitor-triage\"} - min_over_time(tickets_with_triage_counter_total{job=\"service-outage-monitor-triage\"} [1h])) + (tickets_without_triage_counter_total{job=\"service-outage-monitor-triage\"}  - min_over_time(tickets_without_triage_counter_total{job=\"service-outage-monitor-triage\"} [1h]))\n\n"
    }
   ]
  },
  {
   "title": "Tickets with triage processed in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(tickets_with_triage_counter_total{job=\"service-outage-monitor-triage\"} - min_over_time(tickets_with_triage_counter_total{job=\"service-outage-monitor-triage\"} [1h])) "
    }
   ]
  },
  {
   "title": "Tickets without a triage processed in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(tickets_without_triage_counter_total{job=\"service-outage-monitor-triage\"}  - min_over_time(tickets_without_triage_counter_total{job=\"service-outage-monitor-triage\"} [1h]))"
    }
   ]
  },
  {
   "title": " Triage notes appended in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "triage_note_counter_total{job=\"service-outage-monitor-triage\"} - min_over_time(triage_note_counter_total{job=\"service-outage-monitor-triage\"}[1h]) "
    }
   ]
  },
  {
   "title": " Errors trying to get open tickets in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "open_ticket_error_counter_total{job=\"service-outage-monitor-triage\"} - min_over_time(open_ticket_error_counter_total{job=\"service-outage-monitor-triage\"}[1h])"
    }
   ]
  },
  {
   "title": " Errors in the monitoring map in the last 8h",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "monitor_map_error_counter_total{job=\"service-outage-monitor-triage\"} - min_over_time(monitor_map_error_counter_total{job=\"service-outage-monitor-triage\"}[8h])"
    }
   ]
  },
  {
   "title": " Errors trying to append triage notes in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "triage_error_note_counter_total{job=\"service-outage-monitor-triage\"} - min_over_time(triage_error_note_counter_total{job=\"service-outage-monitor-triage\"}[1h]) "
    }
   ]
  }
 ]
}