devices_by_id = [{'serial': 'VC05400028216', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 2837,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200074722', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1692,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200075531', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1565,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200028165', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1607,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05400002729', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1445,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200075575', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1582,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05400001651', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1446,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200074464', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1562,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200071818', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1628,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200014606', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1608,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200056218', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1606,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}},
                 {'serial': 'VC05200043557', 'host': 'metvco03.mettel.net', 'enterprise_id': 105, 'edge_id': 1589,
                  'contacts': {'ticket': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                          'name': 'Royal Brass Help Desk'},
                               'site': {'email': 'helpdesk@royalbrassandhose.com', 'phone': '865-251-9161',
                                        'name': 'Royal Brass Help Desk'}}}]
