devices_by_id = [{'serial': 'VC05200075443', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1905,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200092300', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3223,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200095371', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3490,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200093344', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3373,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200023857', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3290,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200099120', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3608,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200081763', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 2015,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200093654', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3324,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200057782', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 646,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058395', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 775,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200062797', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 727,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200090815', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 766,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200060359', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 740,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200062232', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 738,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200048960', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 269,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200091351', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3251,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200094088', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3109,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200068696', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 993,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200083828', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 2860,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200069673', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1517,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200075468', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1892,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200074782', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3635,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200069273', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1083,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200057785', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 799,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058899', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 985,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200068661', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1042,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200049046', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 316,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200082506', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1953,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200014884', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1614,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200075552', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1904,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200027785', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1616,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200074948', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1598,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200068624', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1125,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200059826', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 774,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200057814', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 770,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200060225', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 712,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058612', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 768,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200093687', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 3138,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200068989', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1427,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058236', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 833,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058431', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 685,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058344', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 773,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200075352', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1597,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058906', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 983,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200058198', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 769,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200074801', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 1659,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200056406', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 446,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05200057975', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 850,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}},
                 {'serial': 'VC05100023564', 'host': 'metvco03.mettel.net', 'enterprise_id': 30, 'edge_id': 91,
                  'contacts': {
                      'ticket': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                                 'name': 'Tenet Telecom'},
                      'site': {'email': 'DL_Tenet_Telecom@nttdata.com', 'phone': 'No Contact Phone Available',
                               'name': 'Tenet Telecom'}}}]
