FROM ubuntu:18.04 AS FEDRAMP

# Input data
ARG NON_ROOT_USER=nroot
ARG REPOSITORY_URL
ARG DOCKER_BASE_IMAGE_VERSION
ARG DEBIAN_FRONTEND=noninteractive

ENV PYTHONUNBUFFERED 1
ENV POETRY_VIRTUALENVS_CREATE=false



# Change to ROOT user to do maintenance/install tasks
USER root

RUN apt-get update && \
    apt-get install --yes --quiet build-essential checkinstall  libreadline-gplv2-dev  libncursesw5-dev  libssl-dev  libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && \
    apt-get install --yes --quiet --no-install-recommends wget software-properties-common
# Create a non-root user
RUN groupadd ${NON_ROOT_USER} --gid 1001 && \
    useradd ${NON_ROOT_USER} --system --create-home --uid 1001 --gid 1001 && \
    chown ${NON_ROOT_USER}:${NON_ROOT_USER} /home/${NON_ROOT_USER}


# Use non-root user
USER ${NON_ROOT_USER}

# Set workdir to user home
WORKDIR /home/${NON_ROOT_USER}

RUN wget https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tgz && \
    tar xzf Python-3.10.4.tgz

RUN cd Python-3.10.4 && \
    ./configure --enable-optimizations --prefix=/home/${NON_ROOT_USER}/.local && \
    make install

RUN wget -q https://install.python-poetry.org -O poetry-install.py && \
    /home/${NON_ROOT_USER}/.local/bin/python3 poetry-install.py

# Copy utils and install with Poetry
COPY --chown=${NON_ROOT_USER}:0 /pyutils_automation/py310 /home/${NON_ROOT_USER}/pyutils_automation/py310
WORKDIR /home/${NON_ROOT_USER}/pyutils_automation/py310
RUN /home/${NON_ROOT_USER}/.local/bin/poetry install --no-root --only main

# Run the service
CMD ["/home/nroot/.local/bin/python3", "-u", "src/app.py"]