{
 "title": "Current SD-WAN Status",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Edges processed in last 10 minutes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "edges_processed", "legendFormat": "Edges processed" }
   ]
  },
  {
   "title": "Edge States ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum by (state) (rate(edge_state_total[10m])) *600",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Link States ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (state) (rate(link_state_total[10m])) *600",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Edge States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (rate(edge_state_total[10m])) *600",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Link States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (rate(link_state_total[10m])) *600",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Edges States by enterprise",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (enterprise_name) (rate(edge_state_total{state='CONNECTED'}[10m])) *600"
    },
    {
     "expr": "sum by (enterprise_name) (rate(edge_state_total{state='OFFLINE'}[10m])) *600"
    },
    {
     "expr": "sum by (enterprise_name) (rate(edge_state_total{state='NEVER_ACTIVATED'}[10m])) *600"
    },
    {
     "expr": "sum by (enterprise_name) (rate(edge_state_total{state='DEGRADED'}[10m])) *600"
    },
    {
     "expr": "sum by (enterprise_name) (rate(edge_state_total[10m])) *600"
    }
   ]
  },
  {
   "title": "Link States by enterprise",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (enterprise_name) (rate(link_state_total{state='STABLE'}[10m])) *600"
    },
    {
     "expr": "sum by (enterprise_name) (rate(link_state_total{state='UNSTABLE'}[10m])) *600"
    },
    {
     "expr": "sum by (enterprise_name) (rate(link_state_total{state='DISCONNECTED'}[10m])) *600"
    },
    {
     "expr": "sum by (enterprise_name) (rate(link_state_total[10m])) *600",
     "legendFormat": "{{enterprise_name}}:{{state}}"
    }
   ]
  }
 ]
}