{
 "title": "Current SD-WAN Status",
 "time": { "from": "now-25m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Edges processed in last cycle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "edges_processed", "legendFormat": "Edges processed" }
   ]
  },
  {
   "title": "Edge States ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (state) ((edge_state_gauge))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Link States ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (state) ((link_state_gauge))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Edge States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (state) ((edge_state_gauge))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Link States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) ((link_state_gauge))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Edges States by enterprise",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (enterprise_name) ((edge_state_gauge{state='CONNECTED'}))"
    },
    {
     "expr": "sum by (enterprise_name) ((edge_state_gauge{state='OFFLINE'}))"
    },
    {
     "expr": "sum by (enterprise_name) ((edge_state_gauge{state='NEVER_ACTIVATED'}))"
    },
    {
     "expr": "sum by (enterprise_name) ((edge_state_gauge{state='DEGRADED'}))"
    },
    {
     "expr": "sum by (enterprise_name) ((edge_state_gauge))"
    }
   ]
  },
  {
   "title": "Link States by enterprise",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (enterprise_name) ((link_state_gauge{state='STABLE'}))"
    },
    {
     "expr": "sum by (enterprise_name) ((link_state_gauge{state='UNSTABLE'}))"
    },
    {
     "expr": "sum by (enterprise_name) ((link_state_gauge{state='DISCONNECTED'}))"
    },
    {
     "expr": "sum by (enterprise_name) ((link_state_gauge))",
     "legendFormat": "{{enterprise_name}}:{{state}}"
    }
   ]
  }
 ]
}