EMAIL_TAGGER_POLLING = 5
RTA_POLLING = 5
GATEWAY_POLLING = 5
EXECUTION = 1

EMAIL_TAGGER = EMAIL_TAGGER_POLLING + EXECUTION
RTA = EMAIL_TAGGER_POLLING + RTA_POLLING + EXECUTION
STANDALONE_RTA = RTA_POLLING + EXECUTION

GATEWAY = GATEWAY_POLLING + EXECUTION
