variable "ENVIRONMENT" {
}

variable "domain" {
  default = "mettel-automation.net"
}

variable "SUBDOMAIN" {
}

variable "BUILD_NUMBER" {
  default = ""
}

variable "NATS_MODULE_VERSION" {
  default = "latest"
}

variable "cidr_base" {
  type = "map"
  default = {
    "production"  = "10.1.0.0/16"
    "dev"         = "10.2.0.0/16"
  }
}

variable "CURRENT_ENVIRONMENT" {
  default = "dev"
  description = "Name of the environment to identify the network resources to be used"
  type = "string"
}

variable "NATS_SERVER_SEED_CLUSTER_PORT" {
  default = 5222
  type = number
  description = "NATS edge server cluster port"
}

variable "NATS_SERVER_SEED_CLIENTS_PORT" {
  default = "4222"
  type = string
  description = "Port for clients in NATS seed node"
}

variable "NATS_SERVER_SEED_CLUSTER_MODE" {
  default = "s"
  type = string
  description = "NATS seed node cluster mode"
}

variable "NATS_SERVER_2_CLUSTER_PORT" {
  default = 5224
  type = number
  description = "NATS server 2 cluster port"
}

variable "NATS_SERVER_2_CLIENTS_PORT" {
  default = "4224"
  type = string
  description = "Port for clients in NATS seed node 2"
}

variable "NATS_SERVER_2_CLUSTER_MODE" {
  default = "n"
  type = string
  description = "NATS server 2 node cluster mode"
}

variable "LAST_CONTACT_RECIPIENT" {
  default = ""
}

variable "PYTHONUNBUFFERED" {
  default = 1
}

variable "EMAIL_ACC_PWD" {
  default = ""
}

variable "MONITORING_SECONDS" {
  default = "600"
}

variable "VELOCLOUD_CREDENTIALS" {
  default = ""
}

variable "VELOCLOUD_VERIFY_SSL" {
  default = "yes"
}

variable "BRUIN_CLIENT_ID" {
  default = ""
}

variable "BRUIN_CLIENT_SECRET" {
  default = ""
}

variable "BRUIN_LOGIN_URL" {
  default = ""
}

variable "BRUIN_BASE_URL" {
  default = ""
}

variable "T7_BASE_URL"{
  default = ""
}

variable "T7_TOKEN"{
  default = ""
}

variable "ALARMS_SUBSCRIPTIONS_EMAIL_ADDRESS" {
  type = "string"
  description = "Email addresses to send notifications generated by alarm of errors and exceptions detected in services"
  default = "xoan.mallon@intelygenz.com"
}

variable "env_network_resources" {
  type = "string"
  description = "Variable for references to common network resources per environment"
  default = "xoan.mallon@intelygenz.com,sancho.munoz@intelygenz.com"
}

variable "alarms_protocol" {
  default     = "email"
  description = "SNS Protocol to use. email or email-json"
  type        = "string"
}

variable "NATS_SERVER_1_CLUSTER_PORT" {
  default = 5223
  type = number
  description = "NATS server 1 cluster port"
}

variable "NATS_SERVER_1_CLIENTS_PORT" {
  default = "4223"
  type = string
  description = "Port for clients in NATS seed node 1"
}

variable "NATS_SERVER_1_CLUSTER_MODE" {
  default = "n"
  type = string
  description = "NATS server 1 node cluster mode"
}

variable "bruin_bridge_desired_tasks" {
  default = 2
  type = number
  description = "Number of desired tasks of microservice bruin-bridge"
}

variable "last_contact_report_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice last-contact-report"
}

variable "metrics_grafana_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice metrics-grafana"
}

variable "metrics_prometheus_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice metrics-prometheus"
}

variable "nats_server_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice nats-server"
}

variable "nats_server_1_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice nats-server-1"
}

variable "nats_server_2_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice nats-server-2"
}

variable "notifier_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice notifier"
}

variable "service_affecting_monitor_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice service-affecting-monitor"
}

variable "service_outage_monitor_desired_tasks" {
  default = 0
  type = number
  description = "Number of desired tasks of microservice service-outage-monitor"
}

variable "service_outage_triage_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice service-outage-triage"
}

variable "sites_monitor_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice sites-monitor"
}

variable "t7_bridge_desired_tasks" {
  default = 1
  type = number
  description = "Number of desired tasks of microservice t7-bridge"
}

variable "velocloud_bridge_desired_tasks" {
  default = 5
  type = number
  description = "Number of desired tasks of microservice velocloud-bridge"
}