# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Workers consume

  Scenario: Mixed group and individual subscribers
    Given an event bus and a the following consumers
      |               |
      | consumer_name |
      | consumer_1    |
      | consumer_2    |
      | consumer_3    |
      | consumer_4    |
    When events are published to the topic "test.topic"
      | event   |
      | event 1 |
      | event 2 |
      | event 3 |
    And consumers are subscribed this way to the topic "test.topic"
      |               |                      |
      | consumer_name | type_of_subscription |
      | consumer_1    | individual           |
      | consumer_2    | group                |
      | consumer_3    | group                |
      | consumer_4    | group                |
    Then each individual consumer will receive all events
    And each group consumer will receive exactly one event

  Scenario: Queue group subscribers
    Given an event bus and a the following consumers
      |               |
      | consumer_name |
      | consumer_1    |
      | consumer_2    |
      | consumer_3    |
    When events are published to the topic "test.topic"
      | event   |
      | event 1 |
      | event 2 |
      | event 3 |
    And consumers are subscribed as group to the topic "test.topic"
    Then each group consumer will receive exactly one event

  Scenario: Individual subscribers
    Given an event bus and the following consumers
      |               |
      | consumer_name |
      | consumer_1    |
      | consumer_2    |
      | consumer_3    |
    When events are published to the topic "test.topic"
      | event   |
      | event 1 |
      | event 2 |
      | event 3 |
    And consumers are subscribed as individual to the topic "test.topic"
    Then each individual consumer will receive all events
