variable "ENVIRONMENT" {
}

variable "CURRENT_ENVIRONMENT" {
  default = "dev"
  description = "Name of the environment to identify the network resources to be used"
  type = "string"
}

variable "alarms_subscriptions_email_addresses" {
  type        = "list"
  description = "Email addresses to send notifications generated by alarm of errors and exceptions detected in services"
  default = ["xoan.mallon@intelygenz.com", "sancho.munoz@intelygenz.com"]
}