{
 "title": "InterMapper Business Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "FEATURE", "query": "InterMapper Outage Monitor" },
   {
    "name": "interval",
    "label": "Scale",
    "query": "5m,30m,1h,3h,6h,12h,1d,3d,7d,14d,30d"
   },
   {
    "name": "event",
    "label": "Event",
    "query": {
     "query": "label_values({feature=~\"$FEATURE\"}, event)"
    }
   },
   { "name": "is_piab", "label": "PIAB", "query": "True, False" }
  ]
 },
 "panels": [
  {
   "title": "All Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval]))",
     "legendFormat": "Tasks Created"
    },
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval]))",
     "legendFormat": "Tasks Re-Opened"
    },
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval]))",
     "legendFormat": "Tasks Auto-Resolved"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by Event",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval])) by (event)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Re-Opened",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Auto-Resolved",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Created by Event",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Tasks Re-Opened by Event",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Tasks Auto-Resolved by Event",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$FEATURE\", event=~\"$event\", is_piab=~\"$is_piab\"}[$interval])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  }
 ]
}