{
 "title": "Service Affecting Business Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "FEATURE", "query": "Service Affecting Monitor" },
   {
    "name": "interval",
    "label": "Scale",
    "query": "5m,30m,1h,3h,6h,12h,1d,3d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({feature=~\"$FEATURE\"}, host)"
    }
   },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values({feature=~\"$FEATURE\", host=~\"$host\"}, client)"
    }
   },
   {
    "name": "trouble",
    "label": "Trouble",
    "query": "Latency, Packet Loss, Jitter, Bandwidth Over Utilization, Circuit Instability"
   },
   { "name": "link_types", "label": "Link Type", "query": "Wired, Wireless" },
   { "name": "has_byob", "label": "BYOB", "query": "True, False" }
  ]
 },
 "panels": [
  {
   "title": "All Tasks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))",
     "legendFormat": "Tasks Created"
    },
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))",
     "legendFormat": "Tasks Re-Opened"
    },
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))",
     "legendFormat": "Tasks Forwarded"
    },
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))",
     "legendFormat": "Tasks Auto-Resolved"
    }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Re-Opened",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Forwarded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Auto-Resolved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by Trouble",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval])) by (trouble)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval])) by (trouble)",
     "legendFormat": "{{trouble}}"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by Trouble",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval])) by (trouble)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval])) by (trouble)",
     "legendFormat": "{{trouble}}"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by BYOB",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval])) by (has_byob)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval])) by (has_byob)",
     "legendFormat": "BYOB: {{has_byob}} "
    }
   ]
  },
  {
   "title": "Tasks Forwarded by Target Queue",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", link_types=~\"$link_types\", has_byob=~\"$has_byob\"}[$interval])) by (target_queue)",
     "legendFormat": "{{target_queue}}"
    }
   ]
  }
 ]
}