{
 "title": "Service Outage Business Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "FEATURE", "query": "Service Outage Monitor" },
   {
    "name": "interval",
    "label": "Scale",
    "query": "5m,30m,1h,3h,6h,12h,1d,3d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({feature=~\"$FEATURE\"}, host)"
    }
   },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values({feature=~\"$FEATURE\", host=~\"$host\"}, client)"
    }
   },
   {
    "name": "outage_type",
    "label": "Outage Type",
    "query": "Hard Down (HA), Hard Down (no HA), Link Down (HA), Link Down (no HA), Soft Down (HA)"
   },
   { "name": "link_types", "label": "Link Type", "query": "Wired, Wireless, Both, None" },
   { "name": "has_byob", "label": "BYOB", "query": "True, False" },
   { "name": "has_digi", "label": "DiGi", "query": "True, False" },
   { "name": "severity", "label": "Severity", "query": "2, 3" }
  ]
 },
 "panels": [
  {
   "title": "All Tasks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Created"
    },
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Re-Opened"
    },
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Forwarded"
    },
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Auto-Resolved"
    }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Re-Opened",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Forwarded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Auto-Resolved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by Severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (severity)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (severity)",
     "legendFormat": "Severity: {{severity}}"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (severity)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (severity)",
     "legendFormat": "Severity: {{severity}}"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by BYOB",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (has_byob)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (has_byob)",
     "legendFormat": "BYOB: {{has_byob}}"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened for DiGi Outages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"True\", severity=~\"$severity\"}[$interval]))\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"True\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Forwarded by Target Queue",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (target_queue)",
     "legendFormat": "{{target_queue}}"
    }
   ]
  },
  {
   "title": "Tasks Created & Re-Opened by Link Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (link_types)\n+\nsum(increase(tasks_reopened_total{feature=~\"$FEATURE\", host=~\"$host\", client=~\"$client\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", severity=~\"$severity\"}[$interval])) by (link_types)",
     "legendFormat": "{{link_types}}"
    }
   ]
  }
 ]
}