{
 "title": "IPA Triage Business Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SD_WAN",
    "query": "Service (Affecting|Outage) Monitor"
   },
   {
    "name": "interval",
    "label": "Scale",
    "query": "5m,30m,1h,3h,6h,12h,1d,3d,7d,14d,30d"
   },
   {
    "name": "feature",
    "label": "Feature",
    "query": "Service Affecting Monitor, Service Outage Monitor, InterMapper Outage Monitor, Hawkeye Outage Monitor, Fraud Monitor"
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({feature=~\"$feature\"}, host)"
    }
   },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values({feature=~\"$feature\", host=~\"$host\"}, client)"
    }
   },
   {
    "name": "trouble",
    "label": "Trouble",
    "query": "Latency, Packet Loss, Jitter, Bandwidth Over Utilization, Circuit Instability, Multiple"
   },
   {
    "name": "outage_type",
    "label": "Outage Type",
    "query": "Hard Down (HA), Hard Down (no HA), Link Down (HA), Link Down (no HA), Soft Down (HA)"
   },
   { "name": "link_types", "label": "Link Type", "query": "Wired, Wireless, Both, None" },
   { "name": "has_byob", "label": "BYOB", "query": "True, False" },
   { "name": "has_digi", "label": "DiGi", "query": "True, False" },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values({feature=~\"$feature\"}, topic)"
    }
   },
   { "name": "severity", "label": "Severity", "query": "2, 3" }
  ]
 },
 "panels": [
  {
   "title": "Tasks Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Re-Opened",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Forwarded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Auto-Resolved",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval])) by (feature)",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Tasks Re-Opened",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval])) by (feature)",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Tasks Forwarded",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval])) by (feature)",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Tasks Auto-Resolved",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval])) by (feature)",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Historical Trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Created"
    },
    {
     "expr": "sum(increase(tasks_reopened_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Re-Opened"
    },
    {
     "expr": "sum(increase(tasks_forwarded_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Forwarded"
    },
    {
     "expr": "sum(increase(tasks_autoresolved_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))",
     "legendFormat": "Tasks Auto-Resolved"
    }
   ]
  },
  {
   "title": "Total Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))\n+\nsum(increase(tasks_reopened_total{feature=~\"$feature\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks to be Worked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tasks_created_total{feature!~\"$SD_WAN\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))\n+\nsum(increase(tasks_reopened_total{feature!~\"$SD_WAN\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))\n+\nsum(increase(tasks_forwarded_total{feature=~\"$SD_WAN\", host=~\"$host\", client=~\"$client\", trouble=~\"$trouble\", outage_type=~\"$outage_type\", link_types=~\"$link_types\", has_byob=~\"$has_byob\", has_digi=~\"$has_digi\", topic=~\"$topic\", severity=~\"$severity\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Work Queue Reduced By",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(tasks_forwarded_total[$interval])) + sum(increase(tasks_autoresolved_total[$interval])))\n/\n(sum(increase(tasks_created_total[$interval])) + sum(increase(tasks_reopened_total[$interval])))"
    }
   ]
  }
 ]
}