{
 "title": "Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "master, develop" },
   {
    "name": "broker_id",
    "label": "Broker Id",
    "query": {
     "query": "label_values(kafka_server_KafkaServer_BrokerState_Value, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_log_Log_Size_Value,topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Velocloud API calls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(velocloud_api_usage_total{}[$__interval])) by (endpoint_)",
     "legendFormat": "{{endpoint_}}"
    }
   ]
  },
  {
   "title": "Broker Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesInPerSec_Count{instance=~\"$broker_id\", topic=~\"$topic\"}[5m])) by (instance)",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesOutPerSec_Count{instance=~\"$broker_id\", topic=~\"$topic\"}[5m])) by (instance)",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Messages Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_BrokerTopicMetrics_MessagesInPerSec_Count{topic=~\"$topic\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesInPerSec_Count{topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesOutPerSec_Count{topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_BrokerTopicMetrics_MessagesInPerSec_Count{instance=~\"$broker_id\", topic=~\"$topic\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesInPerSec_Count{topic=~\".*${env}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesInPerSec_Count{topic=~\".*${env}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Kafka disk usage",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_used_percent" }
   ]
  },
  {
   "title": "Kafka CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\", service=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Kafka connect CPU usage",
   "type": "gauge",
   "description": "Kafka server connect CPU usage",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\", service=\"kafka-connect\"}"
    }
   ]
  },
  {
   "title": "Kafka Memory used",
   "type": "gauge",
   "description": "Kafka memory used",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_available_percent{service=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Memory used kafka connect",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_available_percent{service=\"kafka-connect\"}"
    }
   ]
  }
 ]
}