{
 "title": "Outage Monitor (all instances)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "instance",
    "label": "Outage Monitor instance(s)",
    "query": "service-outage-monitor-1,service-outage-monitor-2,service-outage-monitor-3,service-outage-monitor-4"
   },
   { "name": "namespace", "label": "namespace", "query": { "query": "kube_namespace_created" } }
  ]
 },
 "panels": [
  {
   "title": " Execution time per cycle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "cycle_runtime_gauge{job=\"$instance\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": " Tickets created in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "outage_ticket_counter_total{job=\"$instance\",namespace=~\"$namespace\"} - min_over_time(outage_ticket_counter_total{job=\"$instance\",namespace=~\"$namespace\"}[1h])"
    }
   ]
  },
  {
   "title": " Edges processed in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "outage_monitoring_edge_counter_total{job=\"$instance\",namespace=~\"$namespace\"} - min_over_time(outage_monitoring_edge_counter_total{job=\"$instance\",namespace=~\"$namespace\"}[1h])"
    },
    { "expr": "sub" }
   ]
  },
  {
   "title": " Errors caused by max retries in the past hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_retry_error_counter_total{job=\"$instance\",namespace=~\"$namespace\"} - min_over_time(max_retry_error_counter_total{job=\"$instance\",namespace=~\"$namespace\"}[1h])"
    }
   ]
  },
  {
   "title": " Errors adding to temp cache in the past 8 hours",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "temp_cache_error_counter_total{job=\"$instance\",namespace=~\"$namespace\"} - min_over_time(temp_cache_error_counter_total{job=\"$instance\",namespace=~\"$namespace\"}[8h])"
    }
   ]
  },
  {
   "title": " Errors trying to append the first triage in the last 4 hours",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "first_triage_error_counter_total{job=\"$instance\",namespace=~\"$namespace\"} - min_over_time(first_triage_error_counter_total{job=\"$instance\",namespace=~\"$namespace\"}[4h])"
    }
   ]
  },
  {
   "title": " Tickets auto-resolved in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "autoresolve_counter_total{job=\"$instance\",namespace=~\"$namespace\"} - min_over_time(autoresolve_counter_total{job=\"$instance\",namespace=~\"$namespace\"}[1h])"
    }
   ]
  },
  {
   "title": " Tickets reopened in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "reopened_counter_total{job=\"$instance\",namespace=~\"$namespace\"} - min_over_time(reopened_counter_total{job=\"$instance\",namespace=~\"$namespace\"}[1h])"
    }
   ]
  }
 ]
}