{
 "title": "Bruin API usage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "kube_namespace_created" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=\"/identity/connect/token\", namespace=~\"$namespace\"})",
     "legendFormat": "POST /identity/connect/token"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Inventory"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory/Attribute\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Inventory/Attribute"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory/circuit\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Inventory/circuit"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Site\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Site"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Ticket\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Ticket"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=\"/api/Ticket\", namespace=~\"$namespace\"})",
     "legendFormat": "POST /api/Ticket"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/detail/unpause\", namespace=~\"$namespace\"})",
     "legendFormat": "POST /api/Ticket/<id>/detail/unpause"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=~\"/api/Ticket/[0-9]+/details\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Ticket/<id>/details"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/details/[0-9]+/status\", namespace=~\"$namespace\"})",
     "legendFormat": "PUT /api/Ticket/<id>/details/<id>/status"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/details/work\", namespace=~\"$namespace\"})",
     "legendFormat": "PUT /api/Ticket/<id>/details/work"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=~\"/api/Ticket/[0-9]+/nextresult\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Ticket/<id>/nextresult"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/notes\", namespace=~\"$namespace\"})",
     "legendFormat": "POST /api/Ticket/<id>/notes"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/notes/advanced\", namespace=~\"$namespace\"})",
     "legendFormat": "POST /api/Ticket/<id>/notes/advanced"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/severity\", namespace=~\"$namespace\"})",
     "legendFormat": "PUT /api/Ticket/<id>/severity"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Ticket/basic\", namespace=~\"$namespace\"})",
     "legendFormat": "GET /api/Ticket/basic"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=\"/api/Ticket/repair\", namespace=~\"$namespace\"})",
     "legendFormat": "POST /api/Ticket/repair"
    }
   ]
  },
  {
   "title": "POST /identity/connect/token",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"POST\", endpoint_=\"/identity/connect/token\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=\"/identity/connect/token\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Inventory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Inventory/Attribute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "repeat": "endpoint",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory/Attribute\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory/Attribute\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Inventory/circuit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory/circuit\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Inventory/circuit\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Site",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Site\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Site\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Ticket",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Ticket\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Ticket\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "POST /api/Ticket",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"POST\", endpoint_=\"/api/Ticket\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=\"/api/Ticket\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "POST /api/Ticket/<ticket_id>/detail/unpause",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/detail/unpause\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/detail/unpause\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Ticket/<ticket_id>/details",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=~\"/api/Ticket/[0-9]+/details\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=~\"/api/Ticket/[0-9]+/details\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PUT /api/Ticket/<ticket_id>/details/<detail_id>/status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/details/[0-9]+/status\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/details/[0-9]+/status\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PUT /api/Ticket/<ticket_id>/details/work",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/details/work\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/details/work\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Ticket/<ticket_id>/nextresult",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=~\"/api/Ticket/[0-9]+/nextresult\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=~\"/api/Ticket/[0-9]+/nextresult\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "POST /api/Ticket/<ticket_id>/notes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/notes\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/notes\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "POST /api/Ticket/<ticket_id>/notes/advanced",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/notes/advanced\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=~\"/api/Ticket/[0-9]+/notes/advanced\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PUT /api/Ticket/<ticket_id>/severity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/severity\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"PUT\", endpoint_=~\"/api/Ticket/[0-9]+/severity\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GET /api/Ticket/basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Ticket/basic\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"GET\", endpoint_=\"/api/Ticket/basic\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "POST /api/Ticket/repair",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bruin_api_usage_total{method=\"POST\", endpoint_=\"/api/Ticket/repair\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "sum(bruin_api_usage_total{method=\"POST\", endpoint_=\"/api/Ticket/repair\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}